Repository open-telemetry/opentelemetry-python, pull requests merged in 2019-06, with the labels that each got.

#11 Add initial tracer API
  opentelemetry/__init__.py
  opentelemetry/api/__init__.py
  opentelemetry/api/trace/__init__.py
Labels: api, discussion

#21 Move tracing API into namespace package
  opentelemetry-api/opentelemetry/trace/__init__.py
  opentelemetry/__init__.py
  opentelemetry/api/__init__.py
  opentelemetry/api/trace/__init__.py
Labels: api

#12 Add sphinx docs
  docs/Makefile
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/modules.rst
  docs/opentelemetry.trace.rst
Labels: meta

#30 Add tox and travis, run pylint on builds
  .travis.yml
  tox.ini
Labels: meta

#32 Make Sphinx check for undefined references & .gitignore _build.
  .gitignore
  docs/conf.py
Labels: meta

#35 Set pylint's line length to 79 chars
  .pylintrc
  opentelemetry-api/opentelemetry/trace/__init__.py
Labels: style

#31 Add type check to travis
  mypy.ini
  opentelemetry-api/opentelemetry/__init__.py
  opentelemetry-api/opentelemetry/trace/__init__.py
  opentelemetry-api/setup.py
  tox.ini
Labels: meta
