Repository open-telemetry/opentelemetry-python, pull requests merged in 2019-12, with the labels that each got.

#321 Update CODEOWNERS to include only python-approvers
  .github/CODEOWNERS
Labels: PR:please merge, meta

#299 Update WSGI & Flask integrations to follow new semantic conventions
  .flake8
  ext/opentelemetry-ext-flask/src/opentelemetry/ext/flask/__init__.py
  ext/opentelemetry-ext-flask/tests/test_flask_integration.py
  ext/opentelemetry-ext-wsgi/src/opentelemetry/ext/wsgi/__init__.py
  ext/opentelemetry-ext-wsgi/tests/test_wsgi_middleware.py
Labels: PR:please merge

#324 Add posargs
  tox.ini
Labels: PR:please merge, build & infra

#291 Add eachdist.py to simplify build.
  .flake8
  .gitignore
  .isort.cfg
  CONTRIBUTING.md
  dev-requirements.txt
  eachdist.ini
  ext/opentelemetry-ext-testutil/setup.cfg
  pyproject.toml
  scripts/eachdist.py
  tox.ini
Labels: PR:please merge, build & infra

#330 Work around trace-context failures.
  tox.ini
Labels: bug, build & infra

#332 Update README post-v3 release
  README.md
Labels: release

#319 Adding docs for sdk and integrations
  docs/conf.py
  docs/index.rst
  docs/opentelemetry.ext.flask.rst
  docs/opentelemetry.ext.http_requests.rst
  docs/opentelemetry.ext.jaeger.gen.jaeger.ttypes.rst
  docs/opentelemetry.ext.jaeger.rst
  docs/opentelemetry.ext.pymongo.rst
  docs/opentelemetry.ext.wsgi.rst
  docs/opentelemetry.sdk.context.rst
  docs/opentelemetry.sdk.metrics.rst
  docs/opentelemetry.sdk.trace.export.rst
  docs/opentelemetry.sdk.trace.rst
  docs/opentelemetry.trace.rst
  docs/opentelemetry.trace.sampling.rst
  ext/opentelemetry-ext-opentracing-shim/src/opentelemetry/ext/opentracing_shim/__init__.py
  ext/opentelemetry-ext-pymongo/src/opentelemetry/ext/pymongo/__init__.py
  opentelemetry-api/src/opentelemetry/trace/sampling.py
  opentelemetry-sdk/src/opentelemetry/sdk/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/trace/export/__init__.py
  tox.ini
Labels: needs reviewers

#334 Make @toumorokoshi maintainer in README
  README.md
Labels: meta

#301 Named tracers
  README.md
  examples/basic_tracer/tracer.py
  examples/http/server.py
  examples/http/tracer_client.py
  examples/opentelemetry-example-app/src/opentelemetry_example_app/flask_example.py
  ext/opentelemetry-ext-flask/src/opentelemetry/ext/flask/__init__.py
  ext/opentelemetry-ext-http-requests/src/opentelemetry/ext/http_requests/__init__.py
  ext/opentelemetry-ext-http-requests/tests/test_requests_integration.py
  ext/opentelemetry-ext-jaeger/README.rst
  ext/opentelemetry-ext-jaeger/examples/jaeger_exporter_example.py
  ext/opentelemetry-ext-opentracing-shim/src/opentelemetry/ext/opentracing_shim/__init__.py
  ext/opentelemetry-ext-opentracing-shim/tests/test_shim.py
  ext/opentelemetry-ext-testutil/src/opentelemetry/ext/testutil/wsgitestutil.py
  ext/opentelemetry-ext-wsgi/src/opentelemetry/ext/wsgi/__init__.py
  opentelemetry-api/src/opentelemetry/trace/__init__.py
  opentelemetry-api/src/opentelemetry/util/loader.py
  opentelemetry-api/tests/mypysmoke.py
  opentelemetry-api/tests/test_implementation.py
  opentelemetry-api/tests/test_loader.py
  opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py
  opentelemetry-sdk/tests/test_implementation.py
  opentelemetry-sdk/tests/trace/export/test_export.py
  opentelemetry-sdk/tests/trace/export/test_in_memory_span_exporter.py
  opentelemetry-sdk/tests/trace/test_trace.py
  tests/w3c_tracecontext_validation_server.py
Labels: needs reviewers
