Repository open-telemetry/opentelemetry-python, pull requests merged in 2019-11, with the labels that each got.

#260 Bump version to 0.3.dev0
  examples/opentelemetry-example-app/setup.py
  ext/opentelemetry-ext-azure-monitor/src/opentelemetry/ext/azure_monitor/version.py
  ext/opentelemetry-ext-http-requests/setup.cfg
  ext/opentelemetry-ext-http-requests/src/opentelemetry/ext/http_requests/version.py
  ext/opentelemetry-ext-jaeger/src/opentelemetry/ext/jaeger/version.py
  ext/opentelemetry-ext-opentracing-shim/src/opentelemetry/ext/opentracing_shim/version.py
  ext/opentelemetry-ext-wsgi/src/opentelemetry/ext/wsgi/version.py
  opentelemetry-api/src/opentelemetry/util/version.py
  opentelemetry-sdk/setup.py
  opentelemetry-sdk/src/opentelemetry/sdk/version.py
Labels: release

#261 README updates for alpha v2 release
  README.md
Labels: release

#259 Removing add_link and add_lazy_link from api/sdk
  ext/opentelemetry-ext-jaeger/examples/jaeger_exporter_example.py
  ext/opentelemetry-ext-opentracing-shim/src/opentelemetry/ext/opentracing_shim/__init__.py
  opentelemetry-api/src/opentelemetry/trace/__init__.py
  opentelemetry-api/src/opentelemetry/trace/sampling.py
  opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py
  opentelemetry-sdk/tests/trace/test_trace.py
Labels: api

#272 Remove Azure Exporters out of main repo (master)
  README.md
  ext/opentelemetry-ext-azure-monitor/CHANGELOG.md
  ext/opentelemetry-ext-azure-monitor/README.rst
  ext/opentelemetry-ext-azure-monitor/examples/client.py
  ext/opentelemetry-ext-azure-monitor/examples/server.py
  ext/opentelemetry-ext-azure-monitor/examples/trace.py
  ext/opentelemetry-ext-azure-monitor/setup.cfg
  ext/opentelemetry-ext-azure-monitor/setup.py
  ext/opentelemetry-ext-azure-monitor/src/opentelemetry/ext/azure_monitor/__init__.py
  ext/opentelemetry-ext-azure-monitor/src/opentelemetry/ext/azure_monitor/protocol.py
  ext/opentelemetry-ext-azure-monitor/src/opentelemetry/ext/azure_monitor/trace.py
  ext/opentelemetry-ext-azure-monitor/src/opentelemetry/ext/azure_monitor/util.py
  ext/opentelemetry-ext-azure-monitor/src/opentelemetry/ext/azure_monitor/version.py
  ext/opentelemetry-ext-azure-monitor/tests/__init__.py
  tox.ini
Labels: PR:please merge

#295 Update travis.yml for release of Python 3.8.
  .travis.yml
Labels: PR:please merge, build & infra

#290 Removing create_span from the api
  ext/opentelemetry-ext-flask/src/opentelemetry/ext/flask/__init__.py
  ext/opentelemetry-ext-flask/tests/test_flask_integration.py
  ext/opentelemetry-ext-opentracing-shim/src/opentelemetry/ext/opentracing_shim/__init__.py
  ext/opentelemetry-ext-testutil/src/opentelemetry/ext/testutil/wsgitestutil.py
  ext/opentelemetry-ext-wsgi/src/opentelemetry/ext/wsgi/__init__.py
  ext/opentelemetry-ext-wsgi/tests/test_wsgi_middleware.py
  opentelemetry-api/src/opentelemetry/trace/__init__.py
  opentelemetry-api/tests/trace/test_tracer.py
  opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py
  opentelemetry-sdk/tests/trace/test_trace.py
Labels: PR:please merge
