Repository open-telemetry/opentelemetry-python, pull requests merged in 2019-09, with the labels that each got.

#109 Describe isort's multi_line_output setting
  .isort.cfg
Labels: style

#170 Add link to docs to README
  README.md
Labels: doc

#167 Build and host docs via github action
  .github/workflows/docs.yml
  docs/conf.py
Labels: doc, meta
