Repository open-telemetry/opentelemetry-python, pull requests merged in 2020-09, with the labels that each got.

#1053 Populate resource attributes as per semantic conventions
  exporter/opentelemetry-exporter-jaeger/tests/test_jaeger_exporter.py
  exporter/opentelemetry-exporter-zipkin/tests/test_zipkin_exporter.py
  opentelemetry-sdk/CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/resources/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py
  opentelemetry-sdk/tests/metrics/test_metrics.py
  opentelemetry-sdk/tests/resources/test_resources.py
  opentelemetry-sdk/tests/trace/test_trace.py
  tox.ini
Labels: release:required-for-ga

#1019 Update System Metrics
  instrumentation/opentelemetry-instrumentation-system-metrics/src/opentelemetry/instrumentation/system_metrics/__init__.py
  instrumentation/opentelemetry-instrumentation-system-metrics/tests/test_system_metrics.py
Labels: instrumentation

#1062 Improve BatchExportSpanProcessor
  opentelemetry-sdk/CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/trace/export/__init__.py
  opentelemetry-sdk/tests/trace/export/test_export.py
Labels: release:required-for-ga

#1064 exporter/zipkin: adding support for env var OTEL_EXPORTER_ZIPKIN_ENDPOINT
  exporter/opentelemetry-exporter-zipkin/CHANGELOG.md
  exporter/opentelemetry-exporter-zipkin/src/opentelemetry/exporter/zipkin/__init__.py
  exporter/opentelemetry-exporter-zipkin/tests/test_zipkin_exporter.py
Labels: release:required-for-ga

#1082 sdk: rename resource labels to attributes
  exporter/opentelemetry-exporter-jaeger/src/opentelemetry/exporter/jaeger/__init__.py
  exporter/opentelemetry-exporter-jaeger/tests/test_jaeger_exporter.py
  exporter/opentelemetry-exporter-opencensus/src/opentelemetry/exporter/opencensus/metrics_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp/src/opentelemetry/exporter/otlp/__init__.py
  exporter/opentelemetry-exporter-otlp/src/opentelemetry/exporter/otlp/exporter.py
  exporter/opentelemetry-exporter-zipkin/src/opentelemetry/exporter/zipkin/__init__.py
  exporter/opentelemetry-exporter-zipkin/tests/test_zipkin_exporter.py
  instrumentation/opentelemetry-instrumentation-boto/src/opentelemetry/instrumentation/boto/__init__.py
  instrumentation/opentelemetry-instrumentation-boto/tests/test_boto_instrumentation.py
  instrumentation/opentelemetry-instrumentation-botocore/src/opentelemetry/instrumentation/botocore/__init__.py
  instrumentation/opentelemetry-instrumentation-botocore/tests/test_botocore_instrumentation.py
  opentelemetry-sdk/CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/resources/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py
  opentelemetry-sdk/tests/resources/test_resources.py
Labels: release:required-for-ga

#1085 Rename HTTPTextFormat to TextMapPropagator
  docs/conf.py
  docs/examples/datadog_exporter/server.py
  docs/getting-started.rst
  exporter/opentelemetry-exporter-datadog/src/opentelemetry/exporter/datadog/__init__.py
  exporter/opentelemetry-exporter-datadog/src/opentelemetry/exporter/datadog/propagator.py
  instrumentation/opentelemetry-instrumentation-opentracing-shim/src/opentelemetry/instrumentation/opentracing_shim/__init__.py
  instrumentation/opentelemetry-instrumentation-opentracing-shim/tests/test_shim.py
  instrumentation/opentelemetry-instrumentation-requests/tests/test_requests_integration.py
  opentelemetry-api/CHANGELOG.md
  opentelemetry-api/src/opentelemetry/baggage/propagation/__init__.py
  opentelemetry-api/src/opentelemetry/propagators/__init__.py
  opentelemetry-api/src/opentelemetry/propagators/composite.py
  opentelemetry-api/src/opentelemetry/trace/propagation/textmap.py
  opentelemetry-api/src/opentelemetry/trace/propagation/tracecontext.py
  opentelemetry-api/tests/trace/propagation/test_tracecontexthttptextformat.py
  opentelemetry-sdk/src/opentelemetry/sdk/trace/propagation/b3_format.py
  tests/util/src/opentelemetry/test/mock_textmap.py
Labels: release:required-for-ga

#1070 SpanExporter to not receive span if not sampled
  opentelemetry-sdk/src/opentelemetry/sdk/trace/export/__init__.py
  opentelemetry-sdk/tests/trace/export/test_export.py
Labels: release:required-for-ga, sdk

#1087 Use is_recording flag in requests instrumentation
  instrumentation/opentelemetry-instrumentation-requests/src/opentelemetry/instrumentation/requests/__init__.py
  instrumentation/opentelemetry-instrumentation-requests/tests/test_requests_integration.py
  tests/util/setup.cfg
Labels: release:required-for-ga

#1039 Added Falcon 2.0+ instrumentation
  instrumentation/opentelemetry-instrumentation-falcon/CHANGELOG.md
  instrumentation/opentelemetry-instrumentation-falcon/LICENSE
  instrumentation/opentelemetry-instrumentation-falcon/MANIFEST.in
  instrumentation/opentelemetry-instrumentation-falcon/README.rst
  instrumentation/opentelemetry-instrumentation-falcon/setup.cfg
  instrumentation/opentelemetry-instrumentation-falcon/setup.py
  instrumentation/opentelemetry-instrumentation-falcon/src/opentelemetry/instrumentation/falcon/__init__.py
  instrumentation/opentelemetry-instrumentation-falcon/src/opentelemetry/instrumentation/falcon/version.py
  instrumentation/opentelemetry-instrumentation-falcon/tests/__init__.py
  instrumentation/opentelemetry-instrumentation-falcon/tests/app.py
  instrumentation/opentelemetry-instrumentation-falcon/tests/test_falcon.py
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/bootstrap.py
  tox.ini
Labels: instrumentation

#1018 Added instrumentation for Tornado 6 and above
  instrumentation/opentelemetry-instrumentation-tornado/CHANGELOG.md
  instrumentation/opentelemetry-instrumentation-tornado/LICENSE
  instrumentation/opentelemetry-instrumentation-tornado/MANIFEST.in
  instrumentation/opentelemetry-instrumentation-tornado/README.rst
  instrumentation/opentelemetry-instrumentation-tornado/setup.cfg
  instrumentation/opentelemetry-instrumentation-tornado/setup.py
  instrumentation/opentelemetry-instrumentation-tornado/src/opentelemetry/instrumentation/tornado/__init__.py
  instrumentation/opentelemetry-instrumentation-tornado/src/opentelemetry/instrumentation/tornado/client.py
  instrumentation/opentelemetry-instrumentation-tornado/src/opentelemetry/instrumentation/tornado/version.py
  instrumentation/opentelemetry-instrumentation-tornado/tests/__init__.py
  instrumentation/opentelemetry-instrumentation-tornado/tests/test_instrumentation.py
  instrumentation/opentelemetry-instrumentation-tornado/tests/tornado_test_app.py
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/bootstrap.py
  tests/util/src/opentelemetry/test/test_base.py
  tox.ini
Labels: instrumentation

#1128 Update sampling result names
  opentelemetry-sdk/CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/trace/sampling.py
  opentelemetry-sdk/tests/trace/test_sampling.py
Labels: release:required-for-ga

#1074 exporter/datadog: add support for resource labels and service.name
  docs/examples/datadog_exporter/client.py
  exporter/opentelemetry-exporter-datadog/CHANGELOG.md
  exporter/opentelemetry-exporter-datadog/src/opentelemetry/exporter/datadog/constants.py
  exporter/opentelemetry-exporter-datadog/src/opentelemetry/exporter/datadog/exporter.py
  exporter/opentelemetry-exporter-datadog/tests/test_datadog_exporter.py
Labels: exporters

#1124 Add status to the tags for the Zipkin Exporter
  exporter/opentelemetry-exporter-zipkin/CHANGELOG.md
  exporter/opentelemetry-exporter-zipkin/src/opentelemetry/exporter/zipkin/__init__.py
  exporter/opentelemetry-exporter-zipkin/tests/test_zipkin_exporter.py
Labels: release:required-for-ga

#1096 Merge OTELResourceDetector result when creating resources
  opentelemetry-sdk/CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/resources/__init__.py
  opentelemetry-sdk/tests/metrics/test_metrics.py
  opentelemetry-sdk/tests/resources/test_resources.py
  opentelemetry-sdk/tests/trace/test_trace.py
Labels: release:required-for-ga

#1122 Use is_recording flag in wsgi instrumentation
  instrumentation/opentelemetry-instrumentation-wsgi/src/opentelemetry/instrumentation/wsgi/__init__.py
  instrumentation/opentelemetry-instrumentation-wsgi/tests/test_wsgi_middleware.py
Labels: instrumentation, release:required-for-ga

#992 Django span names according to convention
  instrumentation/opentelemetry-instrumentation-django/CHANGELOG.md
  instrumentation/opentelemetry-instrumentation-django/src/opentelemetry/instrumentation/django/middleware.py
  instrumentation/opentelemetry-instrumentation-django/tests/test_middleware.py
  instrumentation/opentelemetry-instrumentation-django/tests/views.py
Labels: instrumentation

#1132 Cast PyMongo commands as strings
  instrumentation/opentelemetry-instrumentation-pymongo/CHANGELOG.md
  instrumentation/opentelemetry-instrumentation-pymongo/src/opentelemetry/instrumentation/pymongo/__init__.py
  instrumentation/opentelemetry-instrumentation-pymongo/tests/test_pymongo.py
Labels: instrumentation

#1123 Add support for OTEL_PROPAGATORS
  opentelemetry-api/CHANGELOG.md
  opentelemetry-api/setup.cfg
  opentelemetry-api/src/opentelemetry/propagators/__init__.py
  opentelemetry-api/tests/configuration/test_configuration.py
  opentelemetry-api/tests/propagators/test_propagators.py
  opentelemetry-sdk/setup.cfg
Labels: release:required-for-ga

#1120 Add support for OTEL_BSP_* environment variables
  opentelemetry-sdk/CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/trace/export/__init__.py
  opentelemetry-sdk/tests/trace/export/test_export.py
Labels: release:required-for-ga

#1179 Removing the circleci config
  .circleci/config.yml
  README.md
Labels: build & infra

#1080 Add Global Error Handler
  docs/examples/error_hander/README.rst
  docs/examples/error_hander/error_handler_0/README.rst
  docs/examples/error_hander/error_handler_0/setup.cfg
  docs/examples/error_hander/error_handler_0/setup.py
  docs/examples/error_hander/error_handler_0/src/error_handler_0/__init__.py
  docs/examples/error_hander/error_handler_0/src/error_handler_0/version.py
  docs/examples/error_hander/error_handler_1/README.rst
  docs/examples/error_hander/error_handler_1/setup.cfg
  docs/examples/error_hander/error_handler_1/setup.py
  docs/examples/error_hander/error_handler_1/src/error_handler_1/__init__.py
  docs/examples/error_hander/error_handler_1/src/error_handler_1/version.py
  docs/examples/error_hander/example.py
  docs/sdk/error_handler.rst
  docs/sdk/sdk.rst
  opentelemetry-sdk/CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/error_handler/__init__.py
  opentelemetry-sdk/tests/error_handler/__init__.py
  opentelemetry-sdk/tests/error_handler/test_error_handler.py
  scripts/check_for_valid_readme.py
Labels: release:required-for-ga, sdk

#1143 Add support for OTLP v0.5.0
  exporter/opentelemetry-exporter-otlp/CHANGELOG.md
  exporter/opentelemetry-exporter-otlp/src/opentelemetry/exporter/otlp/metrics_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp/src/opentelemetry/exporter/otlp/trace_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp/tests/test_otlp_metric_exporter.py
  exporter/opentelemetry-exporter-otlp/tests/test_otlp_trace_exporter.py
  opentelemetry-proto/src/opentelemetry/proto/collector/logs/v1/logs_service_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/collector/logs/v1/logs_service_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/collector/logs/v1/logs_service_pb2_grpc.py
  opentelemetry-proto/src/opentelemetry/proto/logs/v1/logs_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/logs/v1/logs_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/metrics/experimental/configservice_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/metrics/experimental/configservice_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/metrics/experimental/configservice_pb2_grpc.py
  opentelemetry-proto/src/opentelemetry/proto/metrics/v1/metrics_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/metrics/v1/metrics_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/trace/v1/trace_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/trace/v1/trace_pb2.pyi
  scripts/proto_codegen.sh
Labels: release:required-for-ga

#1185 Move test that imports SDK from the API
  opentelemetry-api/tests/trace/test_globals.py
  opentelemetry-sdk/tests/metrics/test_globals.py
  opentelemetry-sdk/tests/trace/test_globals.py
Labels: api, sdk
