Repository open-telemetry/opentelemetry-python, pull requests merged in 2020-02, with the labels that each got.

#282 Add OpenTracing shim example
  examples/opentracing/README.md
  examples/opentracing/__init__.py
  examples/opentracing/images/jaeger-span-expanded.png
  examples/opentracing/images/jaeger-trace-full.png
  examples/opentracing/main.py
  examples/opentracing/rediscache.py
  examples/opentracing/requirements.txt
  ext/opentelemetry-ext-opentracing-shim/tests/test_shim.py
Labels: doc, ext, needs reviewers, shim

#340 Adding pymongo functional tests
  .travis.yml
  ext/opentelemetry-ext-docker-tests/tests/docker-compose.yml
  ext/opentelemetry-ext-docker-tests/tests/pymongo/test_pymongo_functional.py
  ext/opentelemetry-ext-pymongo/tests/test_pymongo.py
  tox.ini
Labels: needs reviewers

#238 Clean up ProbabilitySampler for 64 bit trace IDs
  opentelemetry-api/src/opentelemetry/trace/sampling.py
  opentelemetry-api/tests/trace/test_sampling.py
Labels: api, needs reviewers, sdk, tracing

#422 Implement MinMaxSumCount aggregator
  examples/metrics/simple_example.py
  examples/metrics/stateful.py
  examples/metrics/stateless.py
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/export/aggregate.py
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/export/batcher.py
  opentelemetry-sdk/tests/metrics/export/test_export.py
  opentelemetry-sdk/tests/metrics/test_metrics.py
Labels: metrics

#378 Prometheus metric exporter
  examples/metrics/prometheus.py
  ext/opentelemetry-ext-prometheus/CHANGELOG.md
  ext/opentelemetry-ext-prometheus/README.rst
  ext/opentelemetry-ext-prometheus/setup.cfg
  ext/opentelemetry-ext-prometheus/setup.py
  ext/opentelemetry-ext-prometheus/src/opentelemetry/ext/prometheus/__init__.py
  ext/opentelemetry-ext-prometheus/src/opentelemetry/ext/prometheus/version.py
  ext/opentelemetry-ext-prometheus/tests/__init__.py
  ext/opentelemetry-ext-prometheus/tests/test_prometheus_exporter.py
  tox.ini
Labels: PR:please merge

#442 Version bump for 0.4a0 release
  examples/opentelemetry-example-app/setup.py
  ext/opentelemetry-ext-dbapi/setup.cfg
  ext/opentelemetry-ext-dbapi/src/opentelemetry/ext/dbapi/version.py
  ext/opentelemetry-ext-flask/src/opentelemetry/ext/flask/version.py
  ext/opentelemetry-ext-http-requests/setup.cfg
  ext/opentelemetry-ext-http-requests/src/opentelemetry/ext/http_requests/version.py
  ext/opentelemetry-ext-jaeger/src/opentelemetry/ext/jaeger/version.py
  ext/opentelemetry-ext-mysql/setup.cfg
  ext/opentelemetry-ext-mysql/src/opentelemetry/ext/mysql/version.py
  ext/opentelemetry-ext-opentracing-shim/src/opentelemetry/ext/opentracing_shim/version.py
  ext/opentelemetry-ext-prometheus/src/opentelemetry/ext/prometheus/version.py
  ext/opentelemetry-ext-psycopg2/setup.cfg
  ext/opentelemetry-ext-psycopg2/src/opentelemetry/ext/psycopg2/version.py
  ext/opentelemetry-ext-pymongo/setup.cfg
  ext/opentelemetry-ext-pymongo/src/opentelemetry/ext/pymongo/version.py
  ext/opentelemetry-ext-testutil/src/opentelemetry/ext/testutil/version.py
  ext/opentelemetry-ext-wsgi/src/opentelemetry/ext/wsgi/version.py
  ext/opentelemetry-ext-zipkin/src/opentelemetry/ext/zipkin/version.py
  opentelemetry-api/src/opentelemetry/util/version.py
  opentelemetry-sdk/setup.py
  opentelemetry-sdk/src/opentelemetry/sdk/version.py
Labels: release

#443 Version bump for 0.5.dev0 on master
  examples/opentelemetry-example-app/setup.py
  ext/opentelemetry-ext-dbapi/setup.cfg
  ext/opentelemetry-ext-dbapi/src/opentelemetry/ext/dbapi/version.py
  ext/opentelemetry-ext-flask/src/opentelemetry/ext/flask/version.py
  ext/opentelemetry-ext-http-requests/setup.cfg
  ext/opentelemetry-ext-http-requests/src/opentelemetry/ext/http_requests/version.py
  ext/opentelemetry-ext-jaeger/src/opentelemetry/ext/jaeger/version.py
  ext/opentelemetry-ext-mysql/setup.cfg
  ext/opentelemetry-ext-mysql/src/opentelemetry/ext/mysql/version.py
  ext/opentelemetry-ext-opentracing-shim/src/opentelemetry/ext/opentracing_shim/version.py
  ext/opentelemetry-ext-prometheus/src/opentelemetry/ext/prometheus/version.py
  ext/opentelemetry-ext-psycopg2/setup.cfg
  ext/opentelemetry-ext-psycopg2/src/opentelemetry/ext/psycopg2/version.py
  ext/opentelemetry-ext-pymongo/setup.cfg
  ext/opentelemetry-ext-pymongo/src/opentelemetry/ext/pymongo/version.py
  ext/opentelemetry-ext-testutil/src/opentelemetry/ext/testutil/version.py
  ext/opentelemetry-ext-wsgi/src/opentelemetry/ext/wsgi/version.py
  ext/opentelemetry-ext-zipkin/src/opentelemetry/ext/zipkin/version.py
  opentelemetry-api/src/opentelemetry/util/version.py
  opentelemetry-sdk/setup.py
  opentelemetry-sdk/src/opentelemetry/sdk/version.py
Labels: release

#429 Adding attach/detach methods as per spec
  opentelemetry-api/src/opentelemetry/context/__init__.py
  opentelemetry-api/src/opentelemetry/context/context.py
  opentelemetry-api/src/opentelemetry/context/contextvars_context.py
  opentelemetry-api/src/opentelemetry/context/threadlocal_context.py
  opentelemetry-api/src/opentelemetry/distributedcontext/__init__.py
  opentelemetry-api/tests/context/base_context.py
  opentelemetry-api/tests/context/test_context.py
  opentelemetry-api/tests/context/test_contextvars_context.py
  opentelemetry-api/tests/context/test_threadlocal_context.py
  opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/trace/export/__init__.py
  opentelemetry-sdk/tests/context/test_asyncio.py
Labels: needs reviewers

#439 Make Counter and MinMaxSumCount aggregators thread safe
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/export/aggregate.py
  opentelemetry-sdk/tests/metrics/export/test_export.py
Labels: metrics

#405 OT Collector trace exporter
  examples/basic_tracer/README.md
  examples/basic_tracer/docker/collector-config.yaml
  examples/basic_tracer/docker/docker-compose.yaml
  examples/basic_tracer/tracer.py
  ext/opentelemetry-ext-otcollector/CHANGELOG.md
  ext/opentelemetry-ext-otcollector/README.rst
  ext/opentelemetry-ext-otcollector/setup.cfg
  ext/opentelemetry-ext-otcollector/setup.py
  ext/opentelemetry-ext-otcollector/src/opentelemetry/ext/otcollector/__init__.py
  ext/opentelemetry-ext-otcollector/src/opentelemetry/ext/otcollector/trace_exporter/__init__.py
  ext/opentelemetry-ext-otcollector/src/opentelemetry/ext/otcollector/util.py
  ext/opentelemetry-ext-otcollector/src/opentelemetry/ext/otcollector/version.py
  ext/opentelemetry-ext-otcollector/tests/__init__.py
  ext/opentelemetry-ext-otcollector/tests/test_otcollector_exporter.py
  tox.ini
Labels: exporters, tracing
