Repository open-telemetry/opentelemetry-python, pull requests merged in 2020-11, with the labels that each got.

#1196 Converted TextMap propagator getter to a class and added keys method
  docs/conf.py
  exporter/opentelemetry-exporter-datadog/src/opentelemetry/exporter/datadog/propagator.py
  exporter/opentelemetry-exporter-datadog/tests/test_datadog_format.py
  instrumentation/opentelemetry-instrumentation-asgi/src/opentelemetry/instrumentation/asgi/__init__.py
  instrumentation/opentelemetry-instrumentation-celery/src/opentelemetry/instrumentation/celery/__init__.py
  instrumentation/opentelemetry-instrumentation-django/src/opentelemetry/instrumentation/django/middleware.py
  instrumentation/opentelemetry-instrumentation-falcon/src/opentelemetry/instrumentation/falcon/__init__.py
  instrumentation/opentelemetry-instrumentation-flask/src/opentelemetry/instrumentation/flask/__init__.py
  instrumentation/opentelemetry-instrumentation-grpc/src/opentelemetry/instrumentation/grpc/_server.py
  instrumentation/opentelemetry-instrumentation-opentracing-shim/src/opentelemetry/instrumentation/opentracing_shim/__init__.py
  instrumentation/opentelemetry-instrumentation-pyramid/src/opentelemetry/instrumentation/pyramid/callbacks.py
  instrumentation/opentelemetry-instrumentation-tornado/src/opentelemetry/instrumentation/tornado/__init__.py
  instrumentation/opentelemetry-instrumentation-wsgi/src/opentelemetry/instrumentation/wsgi/__init__.py
  opentelemetry-api/CHANGELOG.md
  opentelemetry-api/src/opentelemetry/baggage/propagation/__init__.py
  opentelemetry-api/src/opentelemetry/propagators/__init__.py
  opentelemetry-api/src/opentelemetry/propagators/composite.py
  opentelemetry-api/src/opentelemetry/trace/propagation/textmap.py
  opentelemetry-api/src/opentelemetry/trace/propagation/tracecontext.py
  opentelemetry-api/tests/baggage/test_baggage_propagation.py
  opentelemetry-api/tests/propagators/test_global_httptextformat.py
  opentelemetry-api/tests/trace/propagation/test_tracecontexthttptextformat.py
  opentelemetry-sdk/CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/trace/propagation/b3_format.py
  opentelemetry-sdk/tests/trace/propagation/test_b3_format.py
  tests/util/src/opentelemetry/test/mock_textmap.py
Labels: rc1, release:required-for-ga

#1295 Removing TracerProvider coupling from Tracer init
  exporter/opentelemetry-exporter-datadog/tests/test_datadog_exporter.py
  opentelemetry-sdk/CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py
Labels: release:required-for-ga

#1141 [Issue #1107] Add gzip compression support for OTLP exporter
  exporter/opentelemetry-exporter-otlp/CHANGELOG.md
  exporter/opentelemetry-exporter-otlp/src/opentelemetry/exporter/otlp/__init__.py
  exporter/opentelemetry-exporter-otlp/src/opentelemetry/exporter/otlp/exporter.py
Labels: release:required-for-ga

#1242 add optional parameter to record_exception method
  opentelemetry-api/CHANGELOG.md
  opentelemetry-api/src/opentelemetry/trace/span.py
  opentelemetry-sdk/CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py
Labels: rc1, release:required-for-ga

#1356 Update protobuf versions
  dev-requirements.txt
  docs/examples/opentelemetry-example-app/setup.cfg
  exporter/opentelemetry-exporter-opencensus/CHANGELOG.md
  exporter/opentelemetry-exporter-opencensus/setup.cfg
  instrumentation/opentelemetry-instrumentation-grpc/CHANGELOG.md
  instrumentation/opentelemetry-instrumentation-grpc/setup.cfg
  opentelemetry-proto/CHANGELOG.md
  opentelemetry-proto/setup.cfg
Labels: instrumentation

#1361 Document None attribute values as undefined behavior
  opentelemetry-api/src/opentelemetry/trace/span.py
Labels: release:required-for-ga

#1365 Align optional parameters for span related to exceptions, add exception.escaped for record_exception
  opentelemetry-api/src/opentelemetry/trace/__init__.py
  opentelemetry-api/src/opentelemetry/trace/span.py
  opentelemetry-sdk/CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py
  opentelemetry-sdk/tests/trace/test_trace.py
Labels: release:required-for-ga

#1367 Rename MetricRecord to ExportRecord to comply with Metrics Spec
  exporter/opentelemetry-exporter-opencensus/src/opentelemetry/exporter/opencensus/metrics_exporter/__init__.py
  exporter/opentelemetry-exporter-opencensus/tests/test_otcollector_metrics_exporter.py
  exporter/opentelemetry-exporter-otlp/src/opentelemetry/exporter/otlp/metrics_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp/tests/test_otlp_metric_exporter.py
  exporter/opentelemetry-exporter-prometheus/src/opentelemetry/exporter/prometheus/__init__.py
  exporter/opentelemetry-exporter-prometheus/tests/test_prometheus_exporter.py
  opentelemetry-sdk/CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/export/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/export/in_memory_metrics_exporter.py
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/export/processor.py
  opentelemetry-sdk/tests/metrics/export/test_export.py
Labels: metrics, sdk

#1373 Rename Record class in Metrics SDK to Accumulation to follow spec
  opentelemetry-sdk/CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/__init__.py
  opentelemetry-sdk/tests/metrics/export/test_export.py
Labels: metrics, sdk

#1372 Renaming Meter to Accumulator in Metrics SDK context
  opentelemetry-instrumentation/tests/test_metric.py
  opentelemetry-sdk/CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/export/controller.py
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/export/processor.py
Labels: metrics, sdk

#1357 Add Contrib Repo Tests workflow on Core PRs
  .github/workflows/test.yml
  CONTRIBUTING.md
  docs/examples/opentelemetry-example-app/setup.cfg
  eachdist.ini
  tox.ini
Labels: release:required-for-ga

#1036 Automatic exporter/provider setup for opentelemetry-instrument command.
  exporter/opentelemetry-exporter-jaeger/setup.cfg
  exporter/opentelemetry-exporter-opencensus/setup.cfg
  exporter/opentelemetry-exporter-otlp/setup.cfg
  exporter/opentelemetry-exporter-prometheus/setup.cfg
  exporter/opentelemetry-exporter-zipkin/setup.cfg
  opentelemetry-instrumentation/CHANGELOG.md
  opentelemetry-instrumentation/README.rst
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/auto_instrumentation/__init__.py
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/auto_instrumentation/components.py
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py
  opentelemetry-instrumentation/tests/test_auto_tracing.py
  opentelemetry-instrumentation/tests/test_run.py
Labels: release:required-for-ga

#1318 Zipkin exporter v2 api support for protobuf format
  .flake8
  .pylintrc
  exporter/opentelemetry-exporter-zipkin/CHANGELOG.md
  exporter/opentelemetry-exporter-zipkin/setup.cfg
  exporter/opentelemetry-exporter-zipkin/src/opentelemetry/exporter/zipkin/__init__.py
  exporter/opentelemetry-exporter-zipkin/src/opentelemetry/exporter/zipkin/gen/__init__.py
  exporter/opentelemetry-exporter-zipkin/src/opentelemetry/exporter/zipkin/gen/zipkin_pb2.py
  exporter/opentelemetry-exporter-zipkin/src/opentelemetry/exporter/zipkin/gen/zipkin_pb2.pyi
  exporter/opentelemetry-exporter-zipkin/tests/test_zipkin_exporter.py
  pyproject.toml
Labels: rc2, release:required-for-ga
