Repository open-telemetry/opentelemetry-python, pull requests merged in 2020-12, with the labels that each got.

#1374 Add fields property
  .github/workflows/test.yml
  opentelemetry-api/CHANGELOG.md
  opentelemetry-api/src/opentelemetry/baggage/propagation/__init__.py
  opentelemetry-api/src/opentelemetry/propagators/composite.py
  opentelemetry-api/src/opentelemetry/trace/propagation/textmap.py
  opentelemetry-api/src/opentelemetry/trace/propagation/tracecontext.py
  opentelemetry-api/tests/baggage/test_baggage_propagation.py
  opentelemetry-api/tests/propagators/test_composite.py
  opentelemetry-api/tests/trace/propagation/test_tracecontexthttptextformat.py
  opentelemetry-sdk/CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/trace/propagation/b3_format.py
  opentelemetry-sdk/tests/trace/propagation/test_b3_format.py
  tests/util/src/opentelemetry/test/mock_textmap.py
Labels: 1.0.0rc1, api, sdk

#1219 adding support for Jaeger propagator
  opentelemetry-sdk/CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/trace/propagation/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/trace/propagation/jaeger_propagator.py
  opentelemetry-sdk/tests/trace/propagation/test_jaeger_propagator.py
Labels: 1.0.0rc1, release:required-for-ga

#1435 Fix to run the Auto instrumentation example in the docs
  docs/examples/auto-instrumentation/README.rst
  docs/examples/auto-instrumentation/server_instrumented.py
  opentelemetry-sdk/setup.cfg
  opentelemetry-sdk/src/opentelemetry/sdk/trace/export/__init__.py
  opentelemetry-sdk/tests/trace/export/test_export.py
Labels: Skip Changelog

#1467 Upgrade isort and enable black compat mode
  .isort.cfg
  .pylintrc
  dev-requirements.txt
  docs/examples/django/pages/views.py
  docs/examples/opentracing/main.py
  exporter/opentelemetry-exporter-otlp/src/opentelemetry/exporter/otlp/exporter.py
  opentelemetry-api/src/opentelemetry/util/__init__.py
  opentelemetry-api/tests/context/test_contextvars_context.py
  opentelemetry-sdk/src/opentelemetry/sdk/util/__init__.py
  opentelemetry-sdk/tests/context/test_asyncio.py
  scripts/eachdist.py
Labels: Skip Changelog

#1464 Clone the contrib repo for every docs dependency install to fix docs build
  docs-requirements.txt
Labels: Skip Changelog

#1443 [PROPOSAL] Add Performance Testing + SDK Span Performance Tests
  .github/workflows/test.yml
  CONTRIBUTING.md
  opentelemetry-sdk/tests/performance/benchmarks/trace/test_benchmark_trace.py
  tox.ini
Labels: Skip Changelog

#1469 Use gh-pages to save performance benchmarks results
  .github/workflows/test.yml
  CONTRIBUTING.md
  docs/index.rst
  docs/performance/benchmarks.rst
Labels: Skip Changelog

#1473 Fix Benchmarks grouping name
  .github/workflows/test.yml
Labels: Skip Changelog

#1478 Only comment on benchmarks on alert
  .github/workflows/test.yml
Labels: Skip Changelog

#1470 Remove unnecesary contrib packages from docs install
  docs-requirements.txt
Labels: Skip Changelog

#1285 Adding support for array attributes to Zipkin exporter
  CHANGELOG.md
  exporter/opentelemetry-exporter-zipkin/src/opentelemetry/exporter/zipkin/__init__.py
  exporter/opentelemetry-exporter-zipkin/tests/test_zipkin_exporter.py
Labels: 1.0.0rc2, release:required-for-ga

#1463 Update usage for `Meter.create_counter` in tests and examples, clean …
  docs/examples/opencensus-exporter-metrics/collector.py
  docs/getting_started/otlpcollector_example.py
  docs/getting_started/prometheus_example.py
  exporter/opentelemetry-exporter-opencensus/tests/test_otcollector_metrics_exporter.py
  exporter/opentelemetry-exporter-prometheus/src/opentelemetry/exporter/prometheus/__init__.py
Labels: Skip Changelog

#1484 Use uppercase if testing in windows
  opentelemetry-api/tests/configuration/test_configuration.py
Labels: Skip Changelog

#1492 Deleting unused file
  opentelemetry-api/src/opentelemetry/distributedcontext/py.typed
Labels: Skip Changelog

#1498 Set max number of commits in performance graph
  .github/workflows/test.yml
Labels: Skip Changelog

#1491 Add throughput performance tests for OTLP exporter
  .github/workflows/test.yml
  exporter/opentelemetry-exporter-otlp/tests/performance/benchmarks/test_benchmark_trace_exporter.py
Labels: Skip Changelog
