Repository open-telemetry/opentelemetry-python, pull requests merged in 2021-07, with the labels that each got.

#1925 Add excerpt for hotfixes
  .github/workflows/test.yml
  RELEASING.md
Labels: Skip Changelog

#1928 Use BatchSpanProcessor in examples
  docs/examples/auto-instrumentation/client.py
  docs/examples/auto-instrumentation/server_instrumented.py
  docs/examples/auto-instrumentation/server_uninstrumented.py
  docs/examples/basic_tracer/basic_trace.py
  docs/examples/basic_tracer/resources.py
  docs/examples/django/client.py
  docs/examples/django/pages/views.py
  docs/examples/fork-process-model/flask-gunicorn/app.py
  docs/examples/fork-process-model/flask-uwsgi/app.py
  docs/examples/opentracing/main.py
  docs/faq-and-cookbook.rst
  docs/getting_started/flask_example.py
  docs/getting_started/tests/test_flask.py
  docs/getting_started/tracing_example.py
Labels: Skip Changelog

#1942 Do not check every string character
  opentelemetry-api/src/opentelemetry/attributes/__init__.py
Labels: Skip Changelog, api

#1946 Generate semconv constants update for OTel Spec 1.5.0
  CHANGELOG.md
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/resource/__init__.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/trace/__init__.py
  scripts/semconv/generate.sh
Labels: Approve Public API check

#1940 Fix formatting errors in Django instrumentation example docs
  docs/examples/django/README.rst
Labels: Skip Changelog

#1955 Use basename to get file name
  scripts/eachdist.py
Labels: Skip Changelog

#1953 Fix typos in test_handler.py
  opentelemetry-sdk/tests/logs/test_handler.py
Labels: Skip Changelog

#1959 Add opentelemetry-instrumentation
  .github/pull_request_template.md
  CHANGELOG.md
  docs-requirements.txt
  docs/conf.py
  eachdist.ini
  opentelemetry-instrumentation/MANIFEST.in
  opentelemetry-instrumentation/README.rst
  opentelemetry-instrumentation/setup.cfg
  opentelemetry-instrumentation/setup.py
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/auto_instrumentation/__init__.py
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/bootstrap.py
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/bootstrap_gen.py
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/configurator.py
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/dependencies.py
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/distro.py
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/instrumentor.py
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/propagators.py
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/py.typed
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/utils.py
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/version.py
  opentelemetry-instrumentation/tests/__init__.py
  opentelemetry-instrumentation/tests/test_bootstrap.py
  opentelemetry-instrumentation/tests/test_dependencies.py
  opentelemetry-instrumentation/tests/test_distro.py
  opentelemetry-instrumentation/tests/test_instrumentor.py
  opentelemetry-instrumentation/tests/test_propagators.py
  opentelemetry-instrumentation/tests/test_run.py
  opentelemetry-instrumentation/tests/test_utils.py
  scripts/build.sh
  tox.ini
Labels: Approve Public API check

#1974 instrumentation: Add LICENSE + tests
  opentelemetry-instrumentation/LICENSE
  opentelemetry-instrumentation/MANIFEST.in
Labels: Skip Changelog

#1977 Listen for publish events
  .github/workflows/publish.yml
Labels: Skip Changelog

#1980 add ocelotl to maintainers list
  README.md
Labels: Skip Changelog

#1937 Default configurators do more for distros
  CHANGELOG.md
  opentelemetry-distro/setup.cfg
  opentelemetry-distro/src/opentelemetry/distro/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/_configuration/__init__.py
  opentelemetry-sdk/tests/test_configurator.py
Labels: Approve Public API check

#1985 Back to develop after 1.4.0 release
  .github/workflows/test.yml
  eachdist.ini
  exporter/opentelemetry-exporter-jaeger-proto-grpc/src/opentelemetry/exporter/jaeger/proto/grpc/version.py
  exporter/opentelemetry-exporter-jaeger-thrift/src/opentelemetry/exporter/jaeger/thrift/version.py
  exporter/opentelemetry-exporter-jaeger/setup.cfg
  exporter/opentelemetry-exporter-jaeger/src/opentelemetry/exporter/jaeger/version.py
  exporter/opentelemetry-exporter-opencensus/src/opentelemetry/exporter/opencensus/version.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/setup.cfg
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/version.py
  exporter/opentelemetry-exporter-otlp/setup.cfg
  exporter/opentelemetry-exporter-otlp/src/opentelemetry/exporter/otlp/version.py
  exporter/opentelemetry-exporter-zipkin-json/src/opentelemetry/exporter/zipkin/json/version.py
  exporter/opentelemetry-exporter-zipkin-proto-http/setup.cfg
  exporter/opentelemetry-exporter-zipkin-proto-http/src/opentelemetry/exporter/zipkin/proto/http/version.py
  exporter/opentelemetry-exporter-zipkin/setup.cfg
  exporter/opentelemetry-exporter-zipkin/src/opentelemetry/exporter/zipkin/version.py
  opentelemetry-api/src/opentelemetry/version.py
  opentelemetry-distro/setup.cfg
  opentelemetry-distro/src/opentelemetry/distro/version.py
  opentelemetry-instrumentation/setup.cfg
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/bootstrap_gen.py
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/version.py
  opentelemetry-proto/src/opentelemetry/proto/version.py
  opentelemetry-sdk/setup.cfg
  opentelemetry-sdk/src/opentelemetry/sdk/version.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/version.py
  propagator/opentelemetry-propagator-b3/src/opentelemetry/propagators/b3/version.py
  propagator/opentelemetry-propagator-jaeger/src/opentelemetry/propagators/jaeger/version.py
  shim/opentelemetry-opentracing-shim/setup.cfg
  shim/opentelemetry-opentracing-shim/src/opentelemetry/shim/opentracing_shim/version.py
  tests/util/src/opentelemetry/test/version.py
Labels: Skip Changelog

#2002 Remove deprecated @asyncio.coroutine
  opentelemetry-sdk/tests/context/test_asyncio.py
Labels: Skip Changelog

#1984 Make test_jaeger_exporter_thrift more deterministic.
  exporter/opentelemetry-exporter-jaeger-thrift/tests/test_jaeger_exporter_thrift.py
Labels: Skip Changelog
