Repository open-telemetry/opentelemetry-python, pull requests merged in 2021-11, with the labels that each got.

#2251 Add logging signal to main
  CHANGELOG.md
  docs/examples/logs/README.rst
  docs/examples/logs/example.py
  docs/examples/logs/otel-collector-config.yaml
  docs/sdk/logs.export.rst
  docs/sdk/logs.rst
  docs/sdk/logs.severity.rst
  docs/sdk/sdk.rst
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/_log_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/logs/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/logs/test_otlp_logs_exporter.py
  opentelemetry-sdk/setup.cfg
  opentelemetry-sdk/src/opentelemetry/sdk/_logs/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/_logs/export/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/_logs/export/in_memory_log_exporter.py
  opentelemetry-sdk/src/opentelemetry/sdk/_logs/severity.py
  opentelemetry-sdk/src/opentelemetry/sdk/environment_variables.py
  opentelemetry-sdk/tests/logs/__init__.py
  opentelemetry-sdk/tests/logs/test_export.py
  opentelemetry-sdk/tests/logs/test_global_provider.py
  opentelemetry-sdk/tests/logs/test_handler.py
  opentelemetry-sdk/tests/logs/test_multi_log_prcessor.py
Labels: Approve Public API check

#2238 Refactor code using pyupgrade for Python 3.6
  docs/examples/basic_context/implicit_context.py
  docs/examples/datadog_exporter/server.py
  docs/examples/fork-process-model/flask-gunicorn/app.py
  docs/examples/fork-process-model/flask-uwsgi/app.py
  docs/examples/opentracing/rediscache.py
  docs/getting_started/tests/test_flask.py
  docs/getting_started/tests/test_tracing.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/exporter.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/trace_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/performance/benchmarks/test_benchmark_trace_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-http/src/opentelemetry/exporter/otlp/proto/http/trace_exporter/encoder/__init__.py
  exporter/opentelemetry-exporter-zipkin-json/setup.cfg
  exporter/opentelemetry-exporter-zipkin-proto-http/setup.cfg
  opentelemetry-api/tests/baggage/test_baggage_propagation.py
  opentelemetry-api/tests/context/test_contextvars_context.py
  opentelemetry-api/tests/propagators/test_composite.py
  opentelemetry-sdk/tests/performance/resource-usage/trace/profile_resource_usage_batch_export.py
  opentelemetry-sdk/tests/performance/resource-usage/trace/profile_resource_usage_simple_export.py
  propagator/opentelemetry-propagator-b3/src/opentelemetry/propagators/b3/__init__.py
  shim/opentelemetry-opentracing-shim/tests/testbed/otel_ot_shim_tracer.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_active_span_replacement/test_asyncio.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_active_span_replacement/test_threads.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_client_server/test_asyncio.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_client_server/test_threads.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_common_request_handler/request_handler.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_common_request_handler/test_asyncio.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_common_request_handler/test_threads.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_late_span_finish/test_asyncio.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_late_span_finish/test_threads.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_listener_per_request/test_asyncio.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_listener_per_request/test_threads.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_multiple_callbacks/test_asyncio.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_multiple_callbacks/test_threads.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_nested_callbacks/test_asyncio.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_nested_callbacks/test_threads.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_subtask_span_propagation/test_asyncio.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_subtask_span_propagation/test_threads.py
  shim/opentelemetry-opentracing-shim/tests/testbed/utils.py
Labels: Skip Changelog, Approve Public API check

#2261 Remove links to metrics/logs feature branches from docs
  docs/examples/logs/README.rst
  docs/index.rst
Labels: doc, Skip Changelog

#2242 Make batch processor fork aware and reinit when needed
  CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/_logs/export/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/trace/export/__init__.py
  opentelemetry-sdk/tests/logs/test_export.py
  opentelemetry-sdk/tests/trace/export/test_export.py
Labels: Approve Public API check

#2268 Use augmented assignments
  opentelemetry-sdk/src/opentelemetry/sdk/_logs/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py
Labels: Skip Changelog

#2273 Rename opentelemetry-test to opentelemetry-test-utils
  .github/workflows/test.yml
  eachdist.ini
  scripts/build.sh
  shim/opentelemetry-opentracing-shim/setup.cfg
  tests/opentelemetry-test-utils/README.rst
  tests/opentelemetry-test-utils/setup.cfg
  tests/opentelemetry-test-utils/setup.py
  tests/opentelemetry-test-utils/src/opentelemetry/test/asgitestutil.py
  tests/opentelemetry-test-utils/src/opentelemetry/test/concurrency_test.py
  tests/opentelemetry-test-utils/src/opentelemetry/test/globals_test.py
  tests/opentelemetry-test-utils/src/opentelemetry/test/httptest.py
  tests/opentelemetry-test-utils/src/opentelemetry/test/mock_textmap.py
  tests/opentelemetry-test-utils/src/opentelemetry/test/spantestutil.py
  tests/opentelemetry-test-utils/src/opentelemetry/test/test_base.py
  tests/opentelemetry-test-utils/src/opentelemetry/test/version.py
  tests/opentelemetry-test-utils/src/opentelemetry/test/wsgitestutil.py
  tox.ini
Labels: Skip Changelog

#2276 [website_docs] Link to website spec pages
  website_docs/getting-started.md
Labels: Skip Changelog, Approve Public API check

#2271 Use parentheses in PR link
  CHANGELOG.md
Labels: Skip Changelog

#2234 Adds Aggregation and instruments as part of Metrics SDK
  CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/aggregation.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/instrument.py
  opentelemetry-sdk/tests/metrics/test_aggregation.py
Labels: metrics, Approve Public API check

#2285 Improve log message in OTLP exporters
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/exporter.py
  exporter/opentelemetry-exporter-otlp-proto-http/src/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py
Labels: Skip Changelog

#2303 opentelemetry-api: update OTEL_METRICS_EXPORTER variable
  CHANGELOG.md
  opentelemetry-api/src/opentelemetry/environment_variables.py
Labels: Approve Public API check

#2287 Remove hardcoded Zoom link
  README.md
Labels: Skip Changelog
