Repository open-telemetry/opentelemetry-python, pull requests merged in 2021-09, with the labels that each got.

#2085 update index to mention metrics/logs
  docs/index.rst
Labels: Skip Changelog

#2082 Updated website docs
  docs/getting-started.rst
  website_docs/getting-started.md
Labels: Skip Changelog

#1889 let's do this (run tests on windows)
  .github/workflows/test.yml
  docs/getting_started/flask_example.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_common_request_handler/test_asyncio.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_common_request_handler/test_threads.py
  tests/util/src/opentelemetry/test/test_base.py
Labels: Skip Changelog, Approve Public API check

#2105 rename test-core env to opentelemetry
  .github/workflows/test.yml
  CONTRIBUTING.md
  tox.ini
Labels: Skip Changelog

#2109 fix opentelemetry-instrumentation setup.cfg
  opentelemetry-instrumentation/setup.cfg
Labels: Skip Changelog

#2108 remove dependency on contrib repo to run tox
  .flake8
  .github/workflows/test.yml
  .gitignore
  .isort.cfg
  CONTRIBUTING.md
  eachdist.ini
  pyproject.toml
  tox.ini
Labels: Skip Changelog

#2133 use {} instead of dict()
  opentelemetry-api/tests/attributes/test_attributes.py
  opentelemetry-sdk/tests/resources/test_resources.py
  opentelemetry-sdk/tests/trace/test_sampling.py
  opentelemetry-sdk/tests/trace/test_trace.py
Labels: Skip Changelog

#2127 update open calls to pass encoding
  docs/examples/error_handler/error_handler_0/setup.py
  docs/examples/error_handler/error_handler_1/setup.py
  exporter/opentelemetry-exporter-jaeger-proto-grpc/setup.py
  exporter/opentelemetry-exporter-jaeger-thrift/setup.py
  exporter/opentelemetry-exporter-jaeger/setup.py
  exporter/opentelemetry-exporter-opencensus/setup.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/setup.py
  exporter/opentelemetry-exporter-otlp-proto-http/setup.py
  exporter/opentelemetry-exporter-otlp/setup.py
  exporter/opentelemetry-exporter-zipkin-json/setup.py
  exporter/opentelemetry-exporter-zipkin-proto-http/setup.py
  exporter/opentelemetry-exporter-zipkin/setup.py
  opentelemetry-api/setup.py
  opentelemetry-distro/setup.py
  opentelemetry-instrumentation/setup.py
  opentelemetry-proto/setup.py
  opentelemetry-sdk/setup.py
  opentelemetry-semantic-conventions/setup.py
  propagator/opentelemetry-propagator-b3/setup.py
  propagator/opentelemetry-propagator-jaeger/setup.py
  scripts/check_for_valid_readme.py
  scripts/eachdist.py
  shim/opentelemetry-opentracing-shim/setup.py
  tests/util/setup.py
Labels: Skip Changelog

#2118 use timeout in force_flush
  opentelemetry-sdk/src/opentelemetry/sdk/logs/export/__init__.py
Labels: Skip Changelog

#2135 don't use deprecated abstractclassmethod
  propagator/opentelemetry-propagator-b3/tests/test_b3_format.py
Labels: Skip Changelog

#2124 fix imports based on pylint 2.11.0 recommendations
  exporter/opentelemetry-exporter-jaeger-proto-grpc/tests/test_jaeger_exporter_protobuf.py
  opentelemetry-api/src/opentelemetry/trace/propagation/tracecontext.py
  propagator/opentelemetry-propagator-b3/src/opentelemetry/propagators/b3/__init__.py
  propagator/opentelemetry-propagator-jaeger/src/opentelemetry/propagators/jaeger/__init__.py
  propagator/opentelemetry-propagator-jaeger/tests/test_jaeger_propagator.py
Labels: Skip Changelog

#2131 use f-strings where possible
  exporter/opentelemetry-exporter-jaeger-thrift/src/opentelemetry/exporter/jaeger/thrift/send.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/test_otlp_trace_exporter.py
  exporter/opentelemetry-exporter-zipkin-json/src/opentelemetry/exporter/zipkin/node_endpoint.py
  opentelemetry-api/src/opentelemetry/attributes/__init__.py
  opentelemetry-api/src/opentelemetry/trace/__init__.py
  opentelemetry-api/src/opentelemetry/trace/propagation/tracecontext.py
  opentelemetry-api/src/opentelemetry/trace/span.py
  opentelemetry-api/src/opentelemetry/util/_providers.py
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/bootstrap.py
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/dependencies.py
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/propagators.py
  opentelemetry-instrumentation/tests/test_dependencies.py
  opentelemetry-sdk/src/opentelemetry/sdk/_configuration/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/trace/sampling.py
  opentelemetry-sdk/src/opentelemetry/sdk/util/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/util/instrumentation.py
  opentelemetry-sdk/tests/trace/export/test_export.py
  opentelemetry-sdk/tests/trace/test_trace.py
  propagator/opentelemetry-propagator-b3/tests/test_b3_format.py
  propagator/opentelemetry-propagator-jaeger/src/opentelemetry/propagators/jaeger/__init__.py
  scripts/eachdist.py
  scripts/public_symbols_checker.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_common_request_handler/test_asyncio.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_common_request_handler/test_threads.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_listener_per_request/test_asyncio.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_listener_per_request/test_threads.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_nested_callbacks/test_asyncio.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_nested_callbacks/test_threads.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_subtask_span_propagation/test_asyncio.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_subtask_span_propagation/test_threads.py
  tests/util/src/opentelemetry/test/spantestutil.py
  tests/util/src/opentelemetry/test/test_base.py
Labels: Skip Changelog

#2101 Add test base class with local HTTP server.
  CHANGELOG.md
  tests/util/src/opentelemetry/test/httptest.py
Labels: Approve Public API check

#2103 Fix incorrect headers parsing via environment variables
  CHANGELOG.md
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/exporter.py
  exporter/opentelemetry-exporter-otlp-proto-http/src/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-http/tests/test_proto_span_exporter.py
  opentelemetry-api/src/opentelemetry/util/re.py
  opentelemetry-api/tests/util/test_re.py
Labels: Approve Public API check

#2136 removing workflow to automatically close issues
  .github/workflows/close-stale-issues.yml
Labels: Skip Changelog

#2115 Fixing broken link in README
  docs/examples/auto-instrumentation/README.rst
Labels: Skip Changelog

#2146 Fix ReadableSpan import in OTLP grpc exporter
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/trace_exporter/__init__.py
Labels: Skip Changelog

#2139 Add support for OTEL_ATTRIBUTE_COUNT_LIMIT
  CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/environment_variables/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py
  opentelemetry-sdk/tests/trace/test_trace.py
  pyproject.toml
Labels: Approve Public API check

#2155 Fix slow batch processor test for pypy + windows
  opentelemetry-sdk/tests/trace/export/test_export.py
Labels: Skip Changelog

#2119 update to pylint 2.11.0
  dev-requirements.txt
  opentelemetry-api/src/opentelemetry/util/_time.py
  opentelemetry-api/tests/trace/test_proxy.py
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/bootstrap.py
  propagator/opentelemetry-propagator-b3/tests/test_b3_format.py
  shim/opentelemetry-opentracing-shim/tests/testbed/test_listener_per_request/test_asyncio.py
Labels: Skip Changelog

#2159 add assertTraceResponseHeaderMatchesSpan method
  tests/util/src/opentelemetry/test/wsgitestutil.py
Labels: Skip Changelog

#2158 updating bootstrap_gen
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/bootstrap_gen.py
Labels: Skip Changelog
