Repository open-telemetry/opentelemetry-python, pull requests merged in 2021-12, with the labels that each got.

#2253 Adding support for entrypoint loading of log exporters
  CHANGELOG.md
  exporter/opentelemetry-exporter-otlp-proto-grpc/setup.cfg
  opentelemetry-sdk/setup.cfg
  opentelemetry-sdk/src/opentelemetry/sdk/_configuration/__init__.py
  opentelemetry-sdk/tests/test_configurator.py
Labels: Approve Public API check

#2307 rename ConsoleExporter to ConsoleLogExporter
  CHANGELOG.md
  opentelemetry-sdk/setup.cfg
  opentelemetry-sdk/src/opentelemetry/sdk/_logs/export/__init__.py
  opentelemetry-sdk/tests/logs/test_export.py
  opentelemetry-sdk/tests/test_configurator.py
Labels: Approve Public API check

#2296 Refactor Meter and MeterProvider
  opentelemetry-api/src/opentelemetry/util/_time.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/export/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/export/metric_exporter.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/instrument.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/metric_reader.py
  opentelemetry-sdk/tests/metrics/test_metrics.py
Labels: metrics, Skip Changelog, Approve Public API check

#2317 [docs] Include opentelemetry-distro as dep for auto-instrumentation example
  docs/examples/auto-instrumentation/README.rst
Labels: Skip Changelog

#2320 add OTEL_LOGS_EXPORTER env variable
  CHANGELOG.md
  opentelemetry-api/src/opentelemetry/environment_variables.py
  opentelemetry-sdk/src/opentelemetry/sdk/_configuration/__init__.py
Labels: Approve Public API check

#2297 Refactor metrics instrument
  opentelemetry-api/src/opentelemetry/_metrics/instrument.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/instrument.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/measurement.py
  opentelemetry-sdk/tests/metrics/integration_test/test_cpu_time.py
  opentelemetry-sdk/tests/metrics/test_instrument.py
Labels: metrics, Skip Changelog, Approve Public API check

#2325 `tests`: added missing tests
  exporter/opentelemetry-exporter-otlp/tests/test_otlp.py
Labels: Skip Changelog

#2342 Updated contrib SHA
  .github/workflows/test.yml
  opentelemetry-sdk/tests/logs/test_export.py
Labels: Skip Changelog, Approve Public API check
