Repository open-telemetry/opentelemetry-python, pull requests merged in 2021-08, with the labels that each got.

#2007 Remove unused imports
  .flake8
  docs/getting_started/otlpcollector_example.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/exporter.py
  exporter/opentelemetry-exporter-zipkin-json/src/opentelemetry/exporter/zipkin/json/__init__.py
  exporter/opentelemetry-exporter-zipkin-json/src/opentelemetry/exporter/zipkin/json/v1/__init__.py
  exporter/opentelemetry-exporter-zipkin-proto-http/src/opentelemetry/exporter/zipkin/proto/http/__init__.py
  exporter/opentelemetry-exporter-zipkin-proto-http/src/opentelemetry/exporter/zipkin/proto/http/v2/__init__.py
  opentelemetry-api/src/opentelemetry/context/contextvars_context.py
  opentelemetry-api/tests/context/test_contextvars_context.py
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/bootstrap.py
  opentelemetry-sdk/tests/context/test_asyncio.py
  opentelemetry-sdk/tests/performance/resource-usage/trace/profile_resource_usage_batch_export.py
  opentelemetry-sdk/tests/performance/resource-usage/trace/profile_resource_usage_simple_export.py
  propagator/opentelemetry-propagator-jaeger/src/opentelemetry/propagators/jaeger/__init__.py
Labels: Skip Changelog

#2028 Add Nathaniel to approvers list
  README.md
Labels: Skip Changelog

#2025 Add Owais to maintainers list
  README.md
Labels: Skip Changelog

#2026 update codeboten from maintainer -> approver
  README.md
Labels: Skip Changelog

#2036 update contrib SHA
  .github/workflows/test.yml
Labels: Skip Changelog

#2029 Update Jaeger Thrift Exporter documentation example
  exporter/opentelemetry-exporter-jaeger-thrift/src/opentelemetry/exporter/jaeger/thrift/__init__.py
Labels: PR:please merge, Skip Changelog

#2012 unpin opentelemetry-api dependency in instrumentation package
  opentelemetry-instrumentation/setup.cfg
Labels: Skip Changelog

#2040 Fix sampling comment
  opentelemetry-sdk/src/opentelemetry/sdk/trace/sampling.py
Labels: Skip Changelog, Approve Public API check

#2039 Fix typos of “it's” where “its” is meant
  opentelemetry-api/src/opentelemetry/trace/__init__.py
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/auto_instrumentation/__init__.py
  opentelemetry-instrumentation/src/opentelemetry/instrumentation/propagators.py
  opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/trace/__init__.py
Labels: Skip Changelog

#2009 Remove contextvars workaround
  opentelemetry-api/src/opentelemetry/context/aiocontextvarsfix.py
  opentelemetry-api/src/opentelemetry/context/contextvars_context.py
  opentelemetry-api/tests/context/test_contextvars_context.py
Labels: Skip Changelog

#2044 Add support for additional Span Limits
  CHANGELOG.md
  opentelemetry-api/src/opentelemetry/attributes/__init__.py
  opentelemetry-api/tests/attributes/test_attributes.py
  opentelemetry-sdk/src/opentelemetry/sdk/environment_variables/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py
  opentelemetry-sdk/tests/trace/test_trace.py
  tests/util/src/opentelemetry/test/spantestutil.py
Labels: Approve Public API check

#2053 Update getting-started guide
  website_docs/getting-started.md
Labels: Skip Changelog

#2061 docs(auto-instrument): add missing pip install in README
  docs/examples/auto-instrumentation/README.rst
Labels: Skip Changelog

#2054 Fix limit env vars unset/unlimited values
  CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py
  opentelemetry-sdk/tests/trace/test_trace.py
Labels: Approve Public API check

#2056 Add support for `OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT` env var
  CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/environment_variables/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py
  opentelemetry-sdk/tests/trace/test_trace.py
Labels: Approve Public API check

#2077 Update to semantic conventions v1.6.1
  .gitignore
  CHANGELOG.md
  opentelemetry-semantic-conventions/README.rst
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/resource/__init__.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/trace/__init__.py
  scripts/semconv/generate.sh
Labels: Approve Public API check

#2084 Rename base test assertion methods for consistency
  .github/workflows/test.yml
  tests/util/src/opentelemetry/test/test_base.py
Labels: Skip Changelog

#2080 Escape reserved characters in baggage keys
  opentelemetry-api/src/opentelemetry/baggage/propagation/__init__.py
  opentelemetry-api/tests/baggage/test_baggage_propagation.py
Labels: Skip Changelog
