Repository open-telemetry/opentelemetry-python, pull requests merged in 2022-03, with the labels that each got.

#2494 Bump mypy to 0.931
  dev-requirements.txt
  opentelemetry-api/src/opentelemetry/baggage/propagation/__init__.py
  opentelemetry-api/src/opentelemetry/trace/__init__.py
  opentelemetry-api/src/opentelemetry/trace/propagation/tracecontext.py
  opentelemetry-api/src/opentelemetry/trace/span.py
  opentelemetry-api/src/opentelemetry/util/re.py
  tox.ini
Labels: Skip Changelog

#2493 Fix OTLP HTTP Endpoint Usage
  CHANGELOG.md
  exporter/opentelemetry-exporter-otlp-proto-http/src/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-http/tests/test_proto_span_exporter.py
Labels: Approve Public API check

#2391 Adds Views to metrics SDK
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/_view_instrument_match.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/instrument.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/metric_reader_storage.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/sdk_configuration.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/view.py
  opentelemetry-sdk/tests/metrics/test_measurement_consumer.py
  opentelemetry-sdk/tests/metrics/test_metric_reader_storage.py
  opentelemetry-sdk/tests/metrics/test_view.py
  opentelemetry-sdk/tests/metrics/test_view_instrument_match.py
Labels: metrics, Skip Changelog, Approve Public API check

#2497 CONTRIBUTING: add cmd to install tox on first mention of tox
  CONTRIBUTING.md
Labels: Skip Changelog

#2321 `opentelemetry-exporter-prometheus`: restore package
  CHANGELOG.md
  eachdist.ini
  exporter/opentelemetry-exporter-prometheus/LICENSE
  exporter/opentelemetry-exporter-prometheus/MANIFEST.in
  exporter/opentelemetry-exporter-prometheus/README.rst
  exporter/opentelemetry-exporter-prometheus/setup.cfg
  exporter/opentelemetry-exporter-prometheus/setup.py
  exporter/opentelemetry-exporter-prometheus/src/opentelemetry/exporter/prometheus/__init__.py
  exporter/opentelemetry-exporter-prometheus/src/opentelemetry/exporter/prometheus/version.py
  exporter/opentelemetry-exporter-prometheus/tests/__init__.py
  exporter/opentelemetry-exporter-prometheus/tests/test_prometheus_exporter.py
  tox.ini
Labels: Approve Public API check

#2501 Fix SDK observable instruments to emit SDK Measurement
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/instrument.py
  opentelemetry-sdk/tests/metrics/integration_test/test_cpu_time.py
  opentelemetry-sdk/tests/metrics/test_instrument.py
Labels: sdk, metrics, PR:please merge, Skip Changelog

#2499 [docs] add version to get_meter
  docs/examples/metrics/example.py
  docs/getting_started/metrics_example.py
Labels: PR:please merge, Skip Changelog

#2508 Fix prometheus histogram "+Inf" bucket
  exporter/opentelemetry-exporter-prometheus/src/opentelemetry/exporter/prometheus/__init__.py
  exporter/opentelemetry-exporter-prometheus/tests/test_prometheus_exporter.py
Labels: metrics, PR:please merge, Skip Changelog

#2515 Moving owais to approvers
  README.md
Labels: Skip Changelog

#2507 [docs] updating metrics examples
  docs/examples/metrics/example.py
  docs/getting_started/metrics_example.py
Labels: Skip Changelog

#2510 Reset async instrumentation aggregations each collection interval
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/aggregation.py
  opentelemetry-sdk/tests/metrics/test_aggregation.py
Labels: sdk, metrics, Skip Changelog

#2517 datadog-apm: deprecate opentelemetry datadog exporter
  docs/examples/datadog_exporter/README.rst
Labels: Skip Changelog

#2513 Add instructions to fix black and isort errors
  CONTRIBUTING.md
Labels: Skip Changelog

#2535 Small fixes to SpanProcessor docs around shutdown()
  opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py
Labels: doc, Skip Changelog

#2533 Fix delta histogram sum not being reset on collection
  CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/aggregation.py
  opentelemetry-sdk/tests/metrics/test_aggregation.py
Labels: sdk, metrics

#2540 Add InMemoryMetricReader to metrics SDK
  CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/export/__init__.py
  opentelemetry-sdk/tests/metrics/test_in_memory_metric_reader.py
Labels: sdk, metrics

#2544 Add drop aggregation
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/aggregation.py
  opentelemetry-sdk/tests/metrics/test_metric_reader_storage.py
  opentelemetry-sdk/tests/metrics/test_view_instrument_match.py
Labels: sdk, metrics, Skip Changelog

#2551 Fix View doc string
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/view.py
Labels: doc, metrics, Skip Changelog

#2563 [docs] add documentation for no-op components
  opentelemetry-api/src/opentelemetry/_metrics/__init__.py
Labels: Skip Changelog

#2571 Fix typo in metrics sdk docs
  docs/sdk/metrics.rst
Labels: Skip Changelog

#2572 Bump black version
  dev-requirements.txt
Labels: Skip Changelog

#2568 Add type annotations
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/_view_instrument_match.py
Labels: metrics, Skip Changelog

#2543 Add default aggregation
  CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/_view_instrument_match.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/aggregation.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/instrument.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/view.py
  opentelemetry-sdk/tests/metrics/test_aggregation.py
Labels: sdk, metrics

#2566 Update opentelemetry-proto to v0.15.0
  CHANGELOG.md
  opentelemetry-proto/README.rst
  opentelemetry-proto/src/opentelemetry/proto/collector/logs/v1/logs_service_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/collector/metrics/v1/metrics_service_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/collector/trace/v1/trace_service_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/common/v1/common_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/common/v1/common_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/logs/v1/logs_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/logs/v1/logs_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/metrics/v1/metrics_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/metrics/v1/metrics_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/resource/v1/resource_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/resource/v1/resource_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/trace/v1/trace_config_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/trace/v1/trace_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/trace/v1/trace_pb2.pyi
  scripts/proto_codegen.sh
Labels: Approve Public API check

#2576 Check for current point type before warning
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/aggregation.py
  opentelemetry-sdk/tests/metrics/test_aggregation.py
Labels: sdk, metrics, Skip Changelog

#2564 Avoid multiple registration of MetricReaders
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/__init__.py
  opentelemetry-sdk/tests/metrics/test_metrics.py
Labels: sdk, metrics, Skip Changelog

#2574 [docs] adding more metrics documentation
  docs/conf.py
  opentelemetry-api/src/opentelemetry/_metrics/__init__.py
  opentelemetry-api/src/opentelemetry/_metrics/instrument.py
Labels: Skip Changelog
