Repository open-telemetry/opentelemetry-python, pull requests merged in 2022-04, with the labels that each got.

#2587 Fix dependencies for test utils
  tests/opentelemetry-test-utils/setup.cfg
  tox.ini
Labels: Skip Changelog

#2596 Fix bleach version
  dev-requirements.txt
Labels: Skip Changelog

#2592 [docs] update maintainers
  README.md
Labels: Skip Changelog

#2597 Fix typo in example
  opentelemetry-api/src/opentelemetry/propagate/__init__.py
Labels: Skip Changelog

#2409 Add check for duplicate instrument names
  opentelemetry-api/src/opentelemetry/_metrics/__init__.py
  opentelemetry-api/tests/metrics/test_meter.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/__init__.py
  opentelemetry-sdk/tests/metrics/test_metrics.py
Labels: metrics, 1.10.0rc1, Skip Changelog

#2599 Use exceptions to report shutdown result
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/export/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/metric_reader.py
  opentelemetry-sdk/tests/metrics/test_in_memory_metric_reader.py
  opentelemetry-sdk/tests/metrics/test_metrics.py
Labels: Skip Changelog, Approve Public API check

#2605 Fix dependency for otlp exporter
  exporter/opentelemetry-exporter-otlp-proto-grpc/setup.cfg
Labels: Skip Changelog

#2607 Update dependency on testutil
  tests/opentelemetry-test-utils/setup.cfg
Labels: Skip Changelog

#2615 [docs] add more documentation to metrics API
  opentelemetry-api/src/opentelemetry/_metrics/__init__.py
Labels: Skip Changelog

#2620 [docs] SDK documentation fixes
  docs/api/metrics.instrument.rst
  docs/conf.py
  docs/sdk/metrics.export.rst
  docs/sdk/metrics.point.rst
  docs/sdk/metrics.rst
  opentelemetry-api/src/opentelemetry/_metrics/__init__.py
  opentelemetry-api/src/opentelemetry/_metrics/instrument.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/aggregation.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/export/__init__.py
Labels: Skip Changelog

#2583 Add InstrumentationScope and deprecate InstrumentationLibraryInfo
  CHANGELOG.md
  exporter/opentelemetry-exporter-jaeger-proto-grpc/src/opentelemetry/exporter/jaeger/proto/grpc/translate/__init__.py
  exporter/opentelemetry-exporter-jaeger-proto-grpc/tests/test_jaeger_exporter_protobuf.py
  exporter/opentelemetry-exporter-jaeger-thrift/src/opentelemetry/exporter/jaeger/thrift/translate/__init__.py
  exporter/opentelemetry-exporter-jaeger-thrift/tests/test_jaeger_exporter_thrift.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/_log_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/_metric_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/exporter.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/trace_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/logs/test_otlp_logs_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/metrics/test_otlp_metrics_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/test_otlp_trace_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-http/src/opentelemetry/exporter/otlp/proto/http/trace_exporter/encoder/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-http/tests/test_protobuf_encoder.py
  exporter/opentelemetry-exporter-zipkin-json/src/opentelemetry/exporter/zipkin/encoder/__init__.py
  exporter/opentelemetry-exporter-zipkin-json/tests/encoder/common_tests.py
  exporter/opentelemetry-exporter-zipkin-json/tests/encoder/test_v1_json.py
  exporter/opentelemetry-exporter-zipkin-json/tests/encoder/test_v2_json.py
  exporter/opentelemetry-exporter-zipkin-proto-http/tests/encoder/common_tests.py
  exporter/opentelemetry-exporter-zipkin-proto-http/tests/encoder/test_v2_protobuf.py
  opentelemetry-api/src/opentelemetry/trace/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/_logs/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/_view_instrument_match.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/instrument.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/point.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/view.py
  opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/util/instrumentation.py
  opentelemetry-sdk/tests/logs/test_export.py
  opentelemetry-sdk/tests/metrics/test_in_memory_metric_reader.py
  opentelemetry-sdk/tests/metrics/test_metrics.py
  opentelemetry-sdk/tests/metrics/test_periodic_exporting_metric_reader.py
  opentelemetry-sdk/tests/metrics/test_point.py
  opentelemetry-sdk/tests/metrics/test_view.py
  opentelemetry-sdk/tests/metrics/test_view_instrument_match.py
  tests/opentelemetry-test-utils/src/opentelemetry/test/metrictestutil.py
Labels: Approve Public API check

#2630 [docs] adding documentation for aggregation types
  docs/sdk/metrics.aggregation.rst
  docs/sdk/metrics.point.rst
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/aggregation.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/point.py
Labels: Skip Changelog

#2603 Aggregate together data from identical instruments
  opentelemetry-api/src/opentelemetry/_metrics/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/__init__.py
  opentelemetry-sdk/tests/metrics/test_metrics.py
Labels: Skip Changelog

#2335 Run mypy checks on Metrics API
  opentelemetry-api/src/opentelemetry/_metrics/__init__.py
  opentelemetry-api/src/opentelemetry/_metrics/instrument.py
  opentelemetry-api/src/opentelemetry/util/_providers.py
  opentelemetry-sdk/src/opentelemetry/sdk/util/instrumentation.py
  tox.ini
Labels: Skip Changelog

#2642 Convert label sequences to JSON in Prometheus exporter
  exporter/opentelemetry-exporter-prometheus/src/opentelemetry/exporter/prometheus/__init__.py
  exporter/opentelemetry-exporter-prometheus/tests/test_prometheus_exporter.py
Labels: Skip Changelog

#2644 Use JSON formatting for all values except strings
  exporter/opentelemetry-exporter-prometheus/src/opentelemetry/exporter/prometheus/__init__.py
  exporter/opentelemetry-exporter-prometheus/tests/test_prometheus_exporter.py
Labels: Skip Changelog

#2648 Check instrument names and units
  opentelemetry-api/src/opentelemetry/_metrics/_internal/instrument.py
  opentelemetry-api/tests/metrics/test_instruments.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/instrument.py
  opentelemetry-sdk/tests/metrics/test_aggregation.py
  opentelemetry-sdk/tests/metrics/test_instrument.py
Labels: Skip Changelog
