Repository open-telemetry/opentelemetry-python, pull requests merged in 2022-02, with the labels that each got.

#2428 Return noopmeter on invalid name getmeter
  .github/workflows/test.yml
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/__init__.py
  opentelemetry-sdk/tests/metrics/test_metrics.py
Labels: Skip Changelog

#2431 [metrics] add sum attribute to Histogram
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/aggregation.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/point.py
  opentelemetry-sdk/tests/metrics/test_aggregation.py
Labels: Skip Changelog

#2429 [exporter/otlp-proto-grpc] add histogram
  CHANGELOG.md
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/_metric_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/metrics/test_otlp_metrics_exporter.py
Labels: Skip Changelog

#2435 OTLP histo sum
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/_metric_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/metrics/test_otlp_metrics_exporter.py
Labels: Skip Changelog

#2380 Add aggregation temporality conversion algorithm
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/aggregation.py
  opentelemetry-sdk/tests/metrics/test_aggregation.py
Labels: metrics, Skip Changelog, Approve Public API check

#2452 [website_docs] Drop website_docs folder
  scripts/generate_website_docs.sh
  website_docs/_index.md
  website_docs/getting-started.md
Labels: Skip Changelog

#2450 bugfix(auto-instrumentation): attach OTLPHandler to root logger
  CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/_configuration/__init__.py
  opentelemetry-sdk/tests/test_configurator.py
Labels: Approve Public API check

#2458 Only check for public symbols in public packages/modules
  scripts/public_symbols_checker.py
Labels: build & infra, PR:please merge, Skip Changelog

#2461 Bump semantic conventions from 1.6.1 to 1.8.0
  CHANGELOG.md
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/resource/__init__.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/trace/__init__.py
  scripts/semconv/generate.sh
Labels: Approve Public API check

#2379 Merge Asynchronous and Synchronous sum aggregations
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/aggregation.py
  opentelemetry-sdk/tests/metrics/test_aggregation.py
Labels: metrics, Skip Changelog, Approve Public API check

#2400 Add _ViewInstrumentMatch
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/_view_instrument_match.py
  opentelemetry-sdk/tests/metrics/test_view_instrument_match.py
Labels: metrics, Skip Changelog, Approve Public API check

#2466 Bump protobuf from 3.14.0 to 3.15.0 in /docs/examples/fork-process-model/flask-gunicorn
  docs/examples/fork-process-model/flask-gunicorn/requirements.txt
Labels: Skip Changelog, Approve Public API check

#2469 [bugfix] aggregate expects a measurement
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/_view_instrument_match.py
Labels: Skip Changelog

#2468 add check for measurement attributes
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/_view_instrument_match.py
  opentelemetry-sdk/tests/metrics/test_view_instrument_match.py
Labels: Skip Changelog

#2474 pin markupsafe version to 2.0.1
  dev-requirements.txt
  docs-requirements.txt
  tox.ini
Labels: Skip Changelog

#2475 implement to_json for Metric
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/point.py
  opentelemetry-sdk/tests/metrics/test_point.py
Labels: Skip Changelog

#2482 add factories for aggregations
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/aggregation.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/metric_reader_storage.py
  opentelemetry-sdk/tests/metrics/test_aggregation.py
Labels: Skip Changelog

#2484 move metrics util function to test package
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/metrics/test_otlp_metrics_exporter.py
  tests/opentelemetry-test-utils/src/opentelemetry/test/metrictestutil.py
Labels: Skip Changelog

#2492 Bump protobuf from 3.14.0 to 3.15.0 in /docs/examples/fork-process-model/flask-uwsgi
  docs/examples/fork-process-model/flask-uwsgi/requirements.txt
Labels: Skip Changelog

#2490 Fix documentation
  opentelemetry-api/src/opentelemetry/trace/__init__.py
Labels: Skip Changelog
