Repository open-telemetry/opentelemetry-python, pull requests merged in 2022-01, with the labels that each got.

#2333 Add section in FAQ/cookbook for nested spans
  docs/faq-and-cookbook.rst
Labels: Skip Changelog

#2344 helpful propagator entry point loading error message
  opentelemetry-api/src/opentelemetry/propagate/__init__.py
  opentelemetry-api/tests/propagators/test_propagators.py
Labels: Skip Changelog, Approve Public API check

#2355 [otlp-exporter] refactor _translate_attributes
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/_log_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/exporter.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/trace_exporter/__init__.py
Labels: Skip Changelog

#2323 `exporter-otlp`: adding metrics exporter structure
  CHANGELOG.md
  docs/getting_started/metrics_example.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/_metric_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/logs/test_otlp_logs_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/metrics/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/metrics/test_otlp_metrics_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/test_otlp_trace_exporter.py
  exporter/opentelemetry-exporter-otlp/tests/test_otlp.py
  opentelemetry-sdk/setup.cfg
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/data.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/export/__init__.py
  opentelemetry-sdk/tests/test_configurator.py
Labels: Approve Public API check

#2354 [api/sdk] add entrypoint for meter provider
  .github/workflows/test.yml
  opentelemetry-api/setup.cfg
  opentelemetry-sdk/setup.cfg
Labels: Skip Changelog

#2359 Remove metric exporters from MeterProvider
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/__init__.py
Labels: metrics, Skip Changelog

#2350 Support insecure configuration
  .github/workflows/test.yml
  CHANGELOG.md
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/_metric_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/exporter.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/trace_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/logs/test_otlp_logs_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/metrics/test_otlp_metrics_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/test_otlp_trace_exporter.py
  opentelemetry-sdk/src/opentelemetry/sdk/environment_variables.py
Labels: Approve Public API check

#2364 Complete metric exporter format and update OTLP exporter
  CHANGELOG.md
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/_metric_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/metrics/test_otlp_metrics_exporter.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/aggregation.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/data.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/export/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/point.py
Labels: Approve Public API check

#2339 Add measurement consumer
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/instrument.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/measurement_consumer.py
  opentelemetry-sdk/tests/metrics/test_instrument.py
  opentelemetry-sdk/tests/metrics/test_measurement_consumer.py
  opentelemetry-sdk/tests/metrics/test_metrics.py
Labels: metrics, Skip Changelog, Approve Public API check

#2351 Use binary search for histogram values
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/aggregation.py
  opentelemetry-sdk/tests/metrics/test_aggregation.py
Labels: metrics, Skip Changelog

#2372 [docs] fix logs example
  docs/examples/logs/README.rst
  docs/examples/logs/example.py
  docs/examples/logs/otel-collector-config.yaml
Labels: Skip Changelog

#2371 [docs] add metrics examples
  docs/examples/metrics/README.rst
  docs/examples/metrics/example.py
  docs/examples/metrics/otel-collector-config.yaml
  docs/getting_started/metrics_example.py
  docs/sdk/metrics.rst
  docs/sdk/sdk.rst
Labels: Skip Changelog

#2373 Handle duplicate meters
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/__init__.py
  opentelemetry-sdk/tests/metrics/test_metrics.py
Labels: Skip Changelog

#2363 Add NoOpTracer and NoOpTracerProvider classes
  CHANGELOG.md
  opentelemetry-api/setup.cfg
  opentelemetry-api/src/opentelemetry/trace/__init__.py
  opentelemetry-api/tests/test_implementation.py
  opentelemetry-api/tests/trace/test_globals.py
  opentelemetry-api/tests/trace/test_proxy.py
  opentelemetry-api/tests/trace/test_tracer.py
Labels: Approve Public API check

#2370 [exporter/otlp] add support for Sum
  CHANGELOG.md
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/_log_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/_metric_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/exporter.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/trace_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/metrics/test_otlp_metrics_exporter.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/point.py
Labels: Approve Public API check

#2381 use bookmark to skip folderlist when linking
  README.md
Labels: Skip Changelog

#2377 Fix a few ExplicitBucketHistogram issues
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/aggregation.py
  opentelemetry-sdk/tests/metrics/test_aggregation.py
Labels: sdk, metrics, Skip Changelog

#2388 Implement SynchronousMeasurementConsumer
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/measurement_consumer.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/metric_reader_storage.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/sdk_configuration.py
  opentelemetry-sdk/tests/metrics/test_measurement_consumer.py
  opentelemetry-sdk/tests/metrics/test_metrics.py
Labels: sdk, metrics, Skip Changelog, Approve Public API check

#2394 Validate add/record operations for instruments
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/instrument.py
  opentelemetry-sdk/tests/metrics/test_instrument.py
Labels: Skip Changelog, Approve Public API check

#2340 Add periodic exporting metric reader
  opentelemetry-sdk/setup.cfg
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/export/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/metric_reader.py
  opentelemetry-sdk/tests/metrics/test_periodic_exporting_metric_reader.py
Labels: Skip Changelog, Approve Public API check

#2397 Add Python version support policy
  CHANGELOG.md
  README.md
Labels: doc

#2405 Make shutdown function be called always
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/__init__.py
  opentelemetry-sdk/tests/metrics/test_metrics.py
Labels: metrics, Skip Changelog

#2399 fixing documentation and return value
  docs/examples/metrics/example.py
  docs/getting_started/metrics_example.py
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/export/__init__.py
Labels: metrics, Skip Changelog

#2410 [logs] prevent None from causing problems
  CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/_logs/__init__.py
  opentelemetry-sdk/tests/logs/test_log_record.py
Labels: Approve Public API check

#2414 Fix log message
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/__init__.py
  opentelemetry-sdk/tests/metrics/test_metrics.py
Labels: metrics, Skip Changelog

#2417 Slightly decrease wait time
  opentelemetry-sdk/tests/metrics/test_periodic_exporting_metric_reader.py
Labels: metrics, Skip Changelog

#2401 Refactor SDK MeterProvider
  opentelemetry-sdk/src/opentelemetry/sdk/_metrics/__init__.py
  opentelemetry-sdk/tests/metrics/test_metrics.py
Labels: metrics, Skip Changelog, Approve Public API check

#2415 update proto to 0.12.0
  CHANGELOG.md
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/_log_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/trace_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/logs/test_otlp_logs_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/test_otlp_trace_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-http/src/opentelemetry/exporter/otlp/proto/http/trace_exporter/encoder/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-http/tests/test_protobuf_encoder.py
  opentelemetry-proto/src/opentelemetry/proto/logs/v1/logs_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/logs/v1/logs_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/metrics/v1/metrics_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/metrics/v1/metrics_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/trace/v1/trace_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/trace/v1/trace_pb2.pyi
  scripts/proto_codegen.sh
Labels: Approve Public API check

#2424 Update logging component status
  website_docs/_index.md
Labels: Skip Changelog

#2427 Upgraded black to 22.1.0
  dev-requirements.txt
  exporter/opentelemetry-exporter-jaeger-proto-grpc/src/opentelemetry/exporter/jaeger/proto/grpc/translate/__init__.py
  exporter/opentelemetry-exporter-jaeger-proto-grpc/tests/test_jaeger_exporter_protobuf.py
  exporter/opentelemetry-exporter-jaeger-thrift/src/opentelemetry/exporter/jaeger/thrift/translate/__init__.py
  exporter/opentelemetry-exporter-jaeger-thrift/tests/test_jaeger_exporter_thrift.py
  exporter/opentelemetry-exporter-opencensus/tests/test_otcollector_trace_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-http/tests/test_protobuf_encoder.py
  exporter/opentelemetry-exporter-zipkin-json/src/opentelemetry/exporter/zipkin/encoder/__init__.py
  exporter/opentelemetry-exporter-zipkin-json/tests/encoder/common_tests.py
  exporter/opentelemetry-exporter-zipkin-json/tests/encoder/test_v1_json.py
  exporter/opentelemetry-exporter-zipkin-json/tests/encoder/test_v2_json.py
  exporter/opentelemetry-exporter-zipkin-proto-http/tests/encoder/common_tests.py
  exporter/opentelemetry-exporter-zipkin-proto-http/tests/encoder/test_v2_protobuf.py
  opentelemetry-api/src/opentelemetry/trace/span.py
  opentelemetry-sdk/src/opentelemetry/sdk/util/instrumentation.py
  opentelemetry-sdk/tests/trace/test_sampling.py
  scripts/eachdist.py
  tests/opentelemetry-test-utils/setup.cfg
Labels: Skip Changelog
