Repository open-telemetry/opentelemetry-python, pull requests merged in 2022-07, with the labels that each got.

#2796 Fix unit and name regexes
  CHANGELOG.md
  opentelemetry-api/src/opentelemetry/metrics/_internal/instrument.py
  opentelemetry-api/tests/metrics/test_instruments.py
Labels: Skip Changelog

#2814 [chore] update approvers list
  README.md
Labels: Skip Changelog

#2782 Remove eachdist from contributing documentation
  CONTRIBUTING.md
Labels: Skip Changelog

#2811 docs: add examples to show common view scenarios
  docs/examples/views/README.rst
  docs/examples/views/change_aggregation.py
  docs/examples/views/change_name.py
  docs/examples/views/limit_num_of_attrs.py
  docs/examples/views/requirements.txt
Labels: Skip Changelog

#2810 LabelValue can be list of strings
  opentelemetry-sdk/src/opentelemetry/sdk/resources/__init__.py
Labels: Skip Changelog, Approve Public API check

#2818 Remove dead link
  CONTRIBUTING.md
Labels: Skip Changelog

#2819 move tracing sdk setup from setUpClass to setUp
  .github/workflows/test.yml
  tests/opentelemetry-test-utils/src/opentelemetry/test/test_base.py
Labels: Skip Changelog

#2826 docs: add example to show how to drop measurements from an instrument
  docs/examples/views/README.rst
  docs/examples/views/drop_metrics_from_instrument.py
Labels: Skip Changelog

#2832 docs: Add an example for preferred temporality and aggregation for metric reader
  docs/examples/metrics/instruments/README.rst
  docs/examples/metrics/instruments/example.py
  docs/examples/metrics/instruments/otel-collector-config.yaml
  docs/examples/metrics/reader/README.rst
  docs/examples/metrics/reader/preferred_aggregation.py
  docs/examples/metrics/reader/preferred_temporality.py
  docs/examples/metrics/reader/requirements.txt
  docs/examples/metrics/views/README.rst
  docs/examples/metrics/views/change_aggregation.py
  docs/examples/metrics/views/change_name.py
  docs/examples/metrics/views/drop_metrics_from_instrument.py
  docs/examples/metrics/views/limit_num_of_attrs.py
  docs/examples/metrics/views/requirements.txt
Labels: Skip Changelog

#2839 Revert "Python 3.11: Enhanced error locations in tracebacks (#2771)"
  opentelemetry-sdk/tests/trace/test_trace.py
Labels: Skip Changelog

#2696 feat:: Added `--insecure` of CLI argument
  CHANGELOG.md
  exporter/opentelemetry-exporter-jaeger-proto-grpc/src/opentelemetry/exporter/jaeger/proto/grpc/__init__.py
  exporter/opentelemetry-exporter-jaeger-proto-grpc/tests/test_jaeger_exporter_protobuf.py
  opentelemetry-sdk/src/opentelemetry/sdk/environment_variables.py
Labels: Approve Public API check
