Repository open-telemetry/opentelemetry-python, pull requests merged in 2023-06, with the labels that each got.

#3316 Update approvers list
  README.md
Labels: Skip Changelog

#3334 Relax versioning of importlib-metadata
  opentelemetry-api/pyproject.toml
Labels: Skip Changelog

#3348 Update contrib SHA
  .github/workflows/test.yml
Labels: Skip Changelog

#3355 Upgrade opentelemetry-proto to 0.20 and regen
  CHANGELOG.md
  exporter/opentelemetry-exporter-otlp-proto-common/tests/test_metrics_encoder.py
  opentelemetry-proto/src/opentelemetry/proto/collector/logs/v1/logs_service_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/collector/logs/v1/logs_service_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/collector/metrics/v1/metrics_service_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/collector/metrics/v1/metrics_service_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/collector/trace/v1/trace_service_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/collector/trace/v1/trace_service_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/common/v1/common_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/common/v1/common_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/logs/v1/logs_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/logs/v1/logs_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/metrics/v1/metrics_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/metrics/v1/metrics_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/resource/v1/resource_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/trace/v1/trace_config_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/trace/v1/trace_config_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/trace/v1/trace_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/trace/v1/trace_pb2.pyi
  scripts/proto_codegen.sh
Labels: Approve Public API check

#3341 Add unit to view instrument selection criteria
  CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/_internal/view.py
  opentelemetry-sdk/tests/metrics/test_view.py
Labels: PR:please merge

#3351 Add dropped_attributes_count support in exporters
  CHANGELOG.md
  exporter/opentelemetry-exporter-otlp-proto-common/src/opentelemetry/exporter/otlp/proto/common/_internal/_log_encoder/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-common/tests/test_log_encoder.py
  opentelemetry-sdk/src/opentelemetry/sdk/_logs/_internal/__init__.py
  opentelemetry-sdk/tests/logs/test_log_record.py
Labels: PR:please merge

#3318 Add timeout for httpTestBase
  tests/opentelemetry-test-utils/src/opentelemetry/test/httptest.py
Labels: PR:please merge, Skip Changelog

#3259 Show helpful message when propagator is not found
  opentelemetry-api/src/opentelemetry/propagate/__init__.py
  opentelemetry-api/tests/propagators/test_propagators.py
Labels: Skip Changelog

#3357 Remove log messages from console
  opentelemetry-sdk/tests/logs/test_export.py
Labels: Skip Changelog
