Repository open-telemetry/opentelemetry-python, pull requests merged in 2023-10, with the labels that each got.

#3251 Update semconv to 1.21.0
  .codespellrc
  .github/workflows/test.yml
  .gitignore
  CHANGELOG.md
  docs/examples/django/README.rst
  opentelemetry-sdk/tests/trace/test_trace.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/metrics/__init__.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/resource/__init__.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/trace/__init__.py
  scripts/semconv/generate.sh
  scripts/semconv/templates/semantic_attributes.j2
  scripts/semconv/templates/semantic_metrics.j2
Labels: Approve Public API check

#3459 Fix typo causing failing CI
  opentelemetry-sdk/src/opentelemetry/sdk/_configuration/__init__.py
Labels: Skip Changelog

#3413 Prometheus exporter support for auto instrumentation
  CHANGELOG.md
  exporter/opentelemetry-exporter-prometheus/pyproject.toml
  exporter/opentelemetry-exporter-prometheus/src/opentelemetry/exporter/prometheus/__init__.py
  exporter/opentelemetry-exporter-prometheus/tests/test_entrypoints.py
  opentelemetry-sdk/src/opentelemetry/sdk/environment_variables.py
Labels: PR:please merge, Approve Public API check

#3469 Update flask example dependencies
  docs/examples/fork-process-model/flask-gunicorn/requirements.txt
  docs/examples/fork-process-model/flask-uwsgi/requirements.txt
Labels: Skip Changelog
