Repository open-telemetry/opentelemetry-python, pull requests merged in 2023-04, with the labels that each got.

#3231 Update OpenCensus shim to update OpenCensus execution context
  shim/opentelemetry-opencensus-shim/src/opentelemetry/shim/opencensus/_patch.py
  shim/opentelemetry-opencensus-shim/src/opentelemetry/shim/opencensus/_shim_span.py
  shim/opentelemetry-opencensus-shim/src/opentelemetry/shim/opencensus/_shim_tracer.py
  shim/opentelemetry-opencensus-shim/tests/test_shim.py
  shim/opentelemetry-opencensus-shim/tests/test_shim_with_sdk.py
Labels: Skip Changelog

#3248 OpenCensus shim small fix for example code
  docs/examples/opencensus-shim/README.rst
  docs/examples/opencensus-shim/requirements.txt
Labels: Skip Changelog

#3256 remove vendor specific example from doc
  docs/examples/datadog_exporter/README.rst
  docs/examples/datadog_exporter/basic_example.py
  docs/examples/datadog_exporter/client.py
  docs/examples/datadog_exporter/datadog_client.py
  docs/examples/datadog_exporter/server.py
Labels: Skip Changelog, Approve Public API check

#3282 Update contrib repo SHA
  .github/workflows/test.yml
Labels: Skip Changelog

#3265 Select histogram aggregation with environment variables
  CHANGELOG.md
  exporter/opentelemetry-exporter-otlp-proto-common/src/opentelemetry/exporter/otlp/proto/common/_internal/metrics_encoder/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/metric_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/test_otlp_metrics_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-http/src/opentelemetry/exporter/otlp/proto/http/metric_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-http/tests/metrics/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-http/tests/metrics/test_otlp_metrics_exporter.py
  opentelemetry-sdk/src/opentelemetry/sdk/environment_variables.py
Labels: Approve Public API check
