Repository open-telemetry/opentelemetry-python, pull requests merged in 2024-07, with the labels that each got.

#4007 opentelemetry-api: allow importlib-metadata up to 8.0
  opentelemetry-api/pyproject.toml
Labels: Skip Changelog

#4014 Speed up OTLP proto gRPC exporter tests
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/logs/test_otlp_logs_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/test_otlp_exporter_mixin.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/test_otlp_metrics_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/test_otlp_trace_exporter.py
Labels: tests, Skip Changelog

#4011 Fix start_time_unix_nano for delta collection temporality for SumAggregation
  CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/_internal/aggregation.py
  opentelemetry-sdk/tests/metrics/integration_test/test_sum_aggregation.py
Labels: bug

#4017 Remove references to `Log` and `Event` in `LoggerProvider` doc string
  opentelemetry-api/src/opentelemetry/_logs/_internal/__init__.py
Labels: Skip Changelog

#4019 Do not run benchmark tests in CI
  .github/workflows/test.yml
Labels: Skip Changelog

#4022 Remove unnecessary dependencies `pytest`, `flaky` and `pytest-benchmark`
  .github/workflows/test.yml
  dev-requirements.txt
  docs/getting_started/tests/requirements.txt
  exporter/opentelemetry-exporter-opencensus/test-requirements.txt
  exporter/opentelemetry-exporter-otlp-proto-common/test-requirements-0.txt
  exporter/opentelemetry-exporter-otlp-proto-common/test-requirements-1.txt
  exporter/opentelemetry-exporter-otlp-proto-grpc/test-requirements-0.txt
  exporter/opentelemetry-exporter-otlp-proto-grpc/test-requirements-1.txt
  exporter/opentelemetry-exporter-otlp-proto-http/test-requirements-0.txt
  exporter/opentelemetry-exporter-otlp-proto-http/test-requirements-1.txt
  exporter/opentelemetry-exporter-otlp/test-requirements.txt
  exporter/opentelemetry-exporter-prometheus/test-requirements.txt
  exporter/opentelemetry-exporter-zipkin-json/test-requirements.txt
  exporter/opentelemetry-exporter-zipkin-proto-http/test-requirements.txt
  exporter/opentelemetry-exporter-zipkin/test-requirements.txt
  mypy-requirements.txt
  opentelemetry-api/test-requirements.txt
  opentelemetry-proto/test-requirements-0.txt
  opentelemetry-proto/test-requirements-1.txt
  opentelemetry-semantic-conventions/test-requirements.txt
  propagator/opentelemetry-propagator-b3/test-requirements.txt
  propagator/opentelemetry-propagator-jaeger/test-requirements.txt
  shim/opentelemetry-opencensus-shim/test-requirements.txt
  shim/opentelemetry-opentracing-shim/test-requirements.txt
  tests/opentelemetry-test-utils/test-requirements.txt
  tox.ini
Labels: Skip Changelog

#4023 Update opentracing and opencesus docs examples to not use JaegerExporter
  docs/examples/opencensus-shim/README.rst
  docs/examples/opencensus-shim/app.py
  docs/examples/opencensus-shim/requirements.txt
  docs/examples/opentracing/README.rst
  docs/examples/opentracing/main.py
  docs/examples/opentracing/requirements.txt
Labels: Skip Changelog

#4033 Move benchmarks outside of tests directory
  .github/workflows/benchmarks.yml
  .github/workflows/test.yml
  .gitignore
  CONTRIBUTING.md
  opentelemetry-sdk/benchmark-requirements.txt
  opentelemetry-sdk/benchmarks/metrics/test_benchmark_metrics.py
  opentelemetry-sdk/benchmarks/metrics/test_benchmark_metrics_histogram,.py
  opentelemetry-sdk/benchmarks/trace/test_benchmark_trace.py
  opentelemetry-sdk/tests/performance/resource-usage/trace/profile_resource_usage_batch_export.py
  opentelemetry-sdk/tests/performance/resource-usage/trace/profile_resource_usage_simple_export.py
  tox.ini
Labels: Skip Changelog

#3385 Added py.typed in sub-modules confirming to PEP 420
  exporter/opentelemetry-exporter-jaeger-proto-grpc/py.typed
  exporter/opentelemetry-exporter-jaeger-thrift/py.typed
  exporter/opentelemetry-exporter-jaeger/py.typed
  exporter/opentelemetry-exporter-opencensus/py.typed
  exporter/opentelemetry-exporter-otlp-proto-common/py.typed
  exporter/opentelemetry-exporter-otlp-proto-grpc/py.typed
  exporter/opentelemetry-exporter-otlp-proto-http/py.typed
  exporter/opentelemetry-exporter-otlp/py.typed
  exporter/opentelemetry-exporter-prometheus/py.typed
  exporter/opentelemetry-exporter-zipkin-json/py.typed
  exporter/opentelemetry-exporter-zipkin-proto-http/py.typed
  exporter/opentelemetry-exporter-zipkin/py.typed
  opentelemetry-api/py.typed
  opentelemetry-api/pyproject.toml
  opentelemetry-api/src/opentelemetry/_logs/py.typed
  opentelemetry-api/src/opentelemetry/attributes/py.typed
  opentelemetry-api/src/opentelemetry/baggage/py.typed
  opentelemetry-api/src/opentelemetry/context/py.typed
  opentelemetry-api/src/opentelemetry/environment_variables/__init__.py
  opentelemetry-api/src/opentelemetry/environment_variables/py.typed
  opentelemetry-api/src/opentelemetry/metrics/py.typed
  opentelemetry-api/src/opentelemetry/propagate/py.typed
  opentelemetry-api/src/opentelemetry/propagators/py.typed
  opentelemetry-api/src/opentelemetry/trace/py.typed
  opentelemetry-api/src/opentelemetry/util/py.typed
  opentelemetry-api/src/opentelemetry/version/__init__.py
  opentelemetry-api/src/opentelemetry/version/py.typed
  opentelemetry-proto/py.typed
  opentelemetry-proto/pyproject.toml
  opentelemetry-proto/src/opentelemetry/proto/version/__init__.py
  opentelemetry-sdk/py.typed
  opentelemetry-sdk/pyproject.toml
  opentelemetry-sdk/src/opentelemetry/sdk/_configuration/py.typed
  opentelemetry-sdk/src/opentelemetry/sdk/_logs/py.typed
  opentelemetry-sdk/src/opentelemetry/sdk/environment_variables/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/environment_variables/py.typed
  opentelemetry-sdk/src/opentelemetry/sdk/error_handler/py.typed
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/py.typed
  opentelemetry-sdk/src/opentelemetry/sdk/resources/py.typed
  opentelemetry-sdk/src/opentelemetry/sdk/trace/py.typed
  opentelemetry-sdk/src/opentelemetry/sdk/util/py.typed
  opentelemetry-sdk/src/opentelemetry/sdk/version/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/version/py.typed
  opentelemetry-semantic-conventions/py.typed
  opentelemetry-semantic-conventions/pyproject.toml
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/metrics/py.typed
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/resource/py.typed
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/trace/py.typed
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/version/__init__.py
  propagator/opentelemetry-propagator-b3/py.typed
  propagator/opentelemetry-propagator-jaeger/py.typed
Labels: Skip Changelog

#4000 Add missing example requirements
  docs/examples/metrics/instruments/requirements.txt
Labels: Skip Changelog

#3902 Separate lint into several jobs
  .codespellrc
  .github/workflows/lint.yml
  .github/workflows/test.yml
  CONTRIBUTING.md
  docs/getting_started/__init__.py
  docs/getting_started/flask_example.py
  docs/getting_started/tests/requirements.txt
  docs/getting_started/tests/test_flask.py
  exporter/opentelemetry-exporter-zipkin-proto-http/test-requirements.txt
  lint-requirements.txt
  tox.ini
Labels: Skip Changelog

#3986 Skip test case in pypy or windows
  opentelemetry-sdk/tests/trace/export/test_export.py
Labels: Skip Changelog

#4004 Set _LastValueAggregation start_time_unix_nano to None
  exporter/opentelemetry-exporter-otlp-proto-common/tests/test_metrics_encoder.py
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/_internal/aggregation.py
  opentelemetry-sdk/tests/metrics/test_aggregation.py
  tests/opentelemetry-test-utils/src/opentelemetry/test/metrictestutil.py
Labels: Skip Changelog

#4046 add missing dependency - deprecated
  opentelemetry-semantic-conventions/pyproject.toml
Labels: Skip Changelog

#4050 Move benchmarks for b3 propagator and grpc exporter
  exporter/opentelemetry-exporter-otlp-proto-grpc/benchmark-requirements.txt
  exporter/opentelemetry-exporter-otlp-proto-grpc/benchmarks/test_benchmark_trace_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/test-requirements-0.txt
  exporter/opentelemetry-exporter-otlp-proto-grpc/test-requirements-1.txt
  opentelemetry-sdk/test-requirements.txt
  propagator/opentelemetry-propagator-b3/benchmark-requirements.txt
  propagator/opentelemetry-propagator-b3/benchmarks/trace/propagation/test_benchmark_b3_format.py
  propagator/opentelemetry-propagator-b3/test-requirements.txt
  tox.ini
Labels: Skip Changelog

#4052 Add Emídio Neto as an approver
  README.md
Labels: Skip Changelog

#4048 Point pylint to the root directory of every package
  exporter/opentelemetry-exporter-otlp-proto-grpc/benchmarks/test_benchmark_trace_exporter.py
  opentelemetry-api/tests/attributes/test_attributes.py
  opentelemetry-api/tests/logs/test_logger_provider.py
  opentelemetry-api/tests/metrics/test_instruments.py
  opentelemetry-api/tests/metrics/test_meter.py
  opentelemetry-api/tests/metrics/test_meter_provider.py
  opentelemetry-api/tests/metrics/test_subclass_instantiation.py
  opentelemetry-api/tests/propagators/test_global_httptextformat.py
  opentelemetry-api/tests/propagators/test_w3cbaggagepropagator.py
  opentelemetry-api/tests/trace/propagation/test_tracecontexthttptextformat.py
  opentelemetry-api/tests/util/test__providers.py
  opentelemetry-sdk/benchmarks/metrics/test_benchmark_metrics.py
  opentelemetry-sdk/benchmarks/metrics/test_benchmark_metrics_histogram.py
  opentelemetry-sdk/benchmarks/trace/test_benchmark_trace.py
  opentelemetry-sdk/tests/metrics/exponential_histogram/test_exponent_mapping.py
  opentelemetry-sdk/tests/metrics/exponential_histogram/test_exponential_bucket_histogram_aggregation.py
  opentelemetry-sdk/tests/metrics/exponential_histogram/test_logarithm_mapping.py
  opentelemetry-sdk/tests/metrics/integration_test/test_explicit_bucket_histogram_aggregation.py
  opentelemetry-sdk/tests/metrics/test_aggregation.py
  opentelemetry-sdk/tests/metrics/test_backward_compat.py
  opentelemetry-sdk/tests/metrics/test_import.py
  opentelemetry-sdk/tests/metrics/test_in_memory_metric_reader.py
  opentelemetry-sdk/tests/metrics/test_instrument.py
  opentelemetry-sdk/tests/metrics/test_measurement_consumer.py
  opentelemetry-sdk/tests/metrics/test_metric_reader.py
  opentelemetry-sdk/tests/metrics/test_metric_reader_storage.py
  opentelemetry-sdk/tests/metrics/test_metrics.py
  opentelemetry-sdk/tests/metrics/test_periodic_exporting_metric_reader.py
  opentelemetry-sdk/tests/metrics/test_point.py
  opentelemetry-sdk/tests/metrics/test_view.py
  opentelemetry-sdk/tests/metrics/test_view_instrument_match.py
  propagator/opentelemetry-propagator-b3/benchmarks/trace/propagation/test_benchmark_b3_format.py
  tox.ini
Labels: Skip Changelog

#4056 Benchmarks job is failing on CI
  .github/workflows/benchmarks.yml
Labels: Skip Changelog

#4051 fix: grpc endpoint
  docs/examples/logs/README.rst
  docs/examples/logs/otel-collector-config.yaml
  docs/examples/metrics/instruments/README.rst
  docs/examples/metrics/instruments/otel-collector-config.yaml
Labels: Skip Changelog

#4059 fix benchmark sdk ci empty output
  tox.ini
Labels: Skip Changelog

#4064 Remove sklearn from contrib tests
  .github/workflows/test.yml
Labels: Skip Changelog

#4055 Add otlp exporters missing documentation
  docs-requirements.txt
  docs/conf.py
  docs/exporter/otlp/otlp.rst
Labels: doc, Skip Changelog

#3978 Fix `ExponentialBucketHistogramAggregation`
  CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/_internal/aggregation.py
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/_internal/exponential_histogram/buckets.py
  opentelemetry-sdk/tests/metrics/exponential_histogram/test_exponential_bucket_histogram_aggregation.py
  opentelemetry-sdk/tests/metrics/integration_test/test_exponential_bucket_histogram.py
  opentelemetry-sdk/tests/metrics/test_aggregation.py
Labels: bug

#4068 Improve development install instructions on README
  README.md
Labels: Skip Changelog

#4071 [sdk/logs] Replace mocks with real instances where possible
  opentelemetry-sdk/tests/logs/test_handler.py
Labels: Skip Changelog

#4087 Include dummy version upload as part of contributing process to mitigate namespace issues
  CONTRIBUTING.md
  RELEASING.md
Labels: Skip Changelog

#4089 opentelemetry-api: Allow `importlib_metadata<=8.2`
  opentelemetry-api/pyproject.toml
  opentelemetry-api/test-requirements.txt
Labels: Skip Changelog

#4053 Running mypy on SDK resources (following up #3995)
  CHANGELOG.md
  opentelemetry-api/src/opentelemetry/attributes/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/resources/__init__.py
  tox.ini
Labels: ep2024-sprints
