Repository open-telemetry/opentelemetry-python, pull requests merged in 2024-08, with the labels that each got.

#4091 Switch to weaver to generate semantic conventions
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/attributes/aws_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/attributes/browser_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/attributes/cloud_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/attributes/container_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/attributes/db_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/attributes/deployment_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/attributes/error_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/attributes/faas_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/attributes/feature_flag_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/attributes/http_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/attributes/k8s_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/attributes/log_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/attributes/messaging_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/attributes/network_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/attributes/oci_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/attributes/otel_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/attributes/service_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/attributes/system_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/attributes/telemetry_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/attributes/url_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/metrics/process_metrics.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/metrics/rpc_metrics.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/metrics/system_metrics.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/attributes/error_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/attributes/exception_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/attributes/http_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/attributes/network_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/attributes/telemetry_attributes.py
  opentelemetry-semantic-conventions/src/opentelemetry/semconv/attributes/url_attributes.py
  scripts/semconv/generate.sh
  scripts/semconv/templates/common.j2
  scripts/semconv/templates/registry/common.j2
  scripts/semconv/templates/registry/semantic_attributes.j2
  scripts/semconv/templates/registry/semantic_metrics.j2
  scripts/semconv/templates/registry/weaver.yaml
  scripts/semconv/templates/semantic_attributes.j2
  scripts/semconv/templates/semantic_metrics.j2
Labels: Skip Changelog

#3992 sdk: Implement basic os resource detector
  CHANGELOG.md
  opentelemetry-sdk/pyproject.toml
  opentelemetry-sdk/src/opentelemetry/sdk/resources/__init__.py
  opentelemetry-sdk/tests/resources/test_resources.py
Labels: Approve Public API check

#4114 Update metrics instrumentation example README.rst to include collector output
  docs/examples/metrics/instruments/README.rst
Labels: Skip Changelog

#4041 Generate workflow files with a Jinja template
  .github/workflows/contrib_0.yml
  .github/workflows/generate_workflows.py
  .github/workflows/lint.yml
  .github/workflows/lint_0.yml
  .github/workflows/misc_0.yml
  .github/workflows/public-api-check.yml
  .github/workflows/shellcheck.yml
  .github/workflows/test.yml
  .github/workflows/test_0.yml
  .github/workflows/test_1.yml
  tox.ini
Labels: Skip Changelog

#4130 changed path to contributing guide url in contributing.md
  CONTRIBUTING.md
Labels: Skip Changelog

#4132 Broaden accepted values in non-urlencoded headers
  opentelemetry-api/src/opentelemetry/util/re.py
  opentelemetry-api/tests/util/test_re.py
Labels: Skip Changelog

#4116 Implement Client Key and Certificate File Support for All OTLP Exporters
  CHANGELOG.md
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/_log_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/exporter.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/metric_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/trace_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/fixtures/test-client-cert.pem
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/fixtures/test-client-key.pem
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/logs/test_otlp_logs_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/test_otlp_metrics_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/test_otlp_trace_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-http/src/opentelemetry/exporter/otlp/proto/http/_log_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-http/src/opentelemetry/exporter/otlp/proto/http/metric_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-http/src/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-http/tests/metrics/test_otlp_metrics_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-http/tests/test_proto_log_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-http/tests/test_proto_span_exporter.py
  opentelemetry-sdk/src/opentelemetry/sdk/environment_variables/__init__.py
Labels: Approve Public API check

#4139 Handle case when first value is `0` in `test_cumulative_aggregation_with_random_data`
  opentelemetry-sdk/tests/metrics/exponential_histogram/test_exponential_bucket_histogram_aggregation.py
Labels: metrics, Skip Changelog

#4054 Events API implementation
  CHANGELOG.md
  opentelemetry-api/src/opentelemetry/_events/__init__.py
  opentelemetry-api/src/opentelemetry/environment_variables/__init__.py
  opentelemetry-api/tests/events/test_event.py
  opentelemetry-api/tests/events/test_event_logger_provider.py
  opentelemetry-api/tests/events/test_proxy_event.py
  tests/opentelemetry-test-utils/src/opentelemetry/test/globals_test.py
Labels: Approve Public API check

#4137 Reset `start_time_unix_nano` in `_ViewInstrumentMatch` for aggregation creation
  CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/_internal/_view_instrument_match.py
  opentelemetry-sdk/tests/metrics/integration_test/test_time_align.py
  opentelemetry-sdk/tests/metrics/test_view_instrument_match.py
Labels: sdk, metrics

#4127 Add script to populate required checks list
  scripts/add_required_checks.py
Labels: Skip Changelog

#4142 events: test Event name precedence in attributes
  opentelemetry-api/tests/events/test_event.py
Labels: Skip Changelog

#4144 opentelemetry-api: allow importlib-metadata up to 8.4.0
  opentelemetry-api/pyproject.toml
  opentelemetry-api/test-requirements.txt
Labels: Skip Changelog

#4106 opentelemetry-test-utils: add async base test class for asgi
  tests/opentelemetry-test-utils/src/opentelemetry/test/asgitestutil.py
Labels: Skip Changelog

#4147 Add missing `def` in example
  opentelemetry-sdk/src/opentelemetry/sdk/trace/sampling.py
Labels: Skip Changelog

#4151 Remove references to test.yml
  CONTRIBUTING.md
  README.md
  scripts/update_sha.py
Labels: Skip Changelog

#4148 Add new maintainers aabmass and xrmx
  README.md
Labels: Skip Changelog

#4158 Update workflows
  .github/workflows/misc_0.yml
Labels: Skip Changelog

#4165 fix contrib repo sha in workflows
  .github/workflows/contrib_0.yml
  .github/workflows/lint_0.yml
  .github/workflows/misc_0.yml
  .github/workflows/test_0.yml
  .github/workflows/test_1.yml
Labels: Skip Changelog

#4162 fix: typo in sampling docs
  opentelemetry-sdk/src/opentelemetry/sdk/trace/sampling.py
Labels: Skip Changelog
