Repository open-telemetry/opentelemetry-python, pull requests merged in 2024-11, with the labels that each got.

#4244 bump Werkzeug to 3.0.6 in test-requirements
  docs/examples/fork-process-model/flask-gunicorn/requirements.txt
  docs/examples/fork-process-model/flask-uwsgi/requirements.txt
  docs/getting_started/tests/requirements.txt
Labels: Skip Changelog

#4258 Regenerate workflows for contrib on core
  .github/workflows/contrib_0.yml
Labels: Skip Changelog

#4257 Fix stable READTHEDOCS build
  .readthedocs.yml
Labels: Skip Changelog

#4251 Fix: filter exemplar for observable instrument and export of exemplar without trace and span ids
  CHANGELOG.md
  exporter/opentelemetry-exporter-otlp-proto-common/src/opentelemetry/exporter/otlp/proto/common/_internal/metrics_encoder/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-common/tests/test_metrics_encoder.py
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/_internal/exemplar/exemplar.py
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/_internal/exemplar/exemplar_reservoir.py
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/_internal/measurement_consumer.py
  opentelemetry-sdk/tests/metrics/integration_test/test_exemplars.py
  opentelemetry-sdk/tests/metrics/test_measurement_consumer.py
Labels: sdk, metrics

#4265 Add install toml to workflows
  .github/workflows/prepare-patch-release.yml
  .github/workflows/prepare-release-branch.yml
  .github/workflows/release.yml
Labels: Skip Changelog

#4273 Remove updating CHANGELOG step in release workflow
  .github/workflows/release.yml
Labels: Skip Changelog

#4280 [release/v1.28.x-0.49bx] Remove updating CHANGELOG step in release workflow (#4273)
  .github/workflows/release.yml
Labels: Skip generate-workflows

#4282 [release/v1.28.x-0.49bx] Support logs with no body (#4276)
  CHANGELOG.md
  exporter/opentelemetry-exporter-otlp-proto-common/src/opentelemetry/exporter/otlp/proto/common/_internal/_log_encoder/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-common/tests/test_log_encoder.py
Labels: Skip generate-workflows

#4283 [release/v1.28.x-0.49bx] opentelemetry-sdk: setup EventLogger when initializing logging (#4270)
  CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/_configuration/__init__.py
  opentelemetry-sdk/tests/test_configurator.py
Labels: Skip generate-workflows

#4287 Fix prepare patch release workflow
  .github/scripts/update-version-patch.sh
  .github/workflows/prepare-patch-release.yml
  scripts/eachdist.py
Labels: Skip generate-workflows

#4289 [v1.28.x-0.49bx] Fix eachdist.py patch release to not add extra space
  .github/scripts/update-version-patch.sh
  scripts/eachdist.py
Labels: Skip generate-workflows

#4291 Cherry pick patch release workflow fixes from release branch
  .github/scripts/update-version-patch.sh
  .github/workflows/prepare-patch-release.yml
  scripts/eachdist.py
Labels: Skip Changelog

#4274 Update RELEASING.md
  RELEASING.md
Labels: Skip Changelog

#4308 Update RELEASING.md to start a ReadTheDocs build for stable
  .github/rtd-build-instructions.png
  RELEASING.md
Labels: Skip Changelog

#4216 Use `LogRecord.getMessage` to get OTLP body
  CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/_logs/_internal/__init__.py
  opentelemetry-sdk/tests/logs/test_export.py
Labels: logging

#4302 infra: remove generate contrib workflows from core
  .github/workflows/contrib.yml
  .github/workflows/contrib_0.yml
  .github/workflows/generate_workflows.py
Labels: Skip Changelog

#4334 infra: update misc workflows to py311
  .github/workflows/misc_0.yml
Labels: Skip Changelog
