Repository open-telemetry/opentelemetry-python, pull requests merged in 2024-04, with the labels that each got.

#3812 Remove logs API proxy test's dependency on SDK
  opentelemetry-api/tests/logs/test_proxy.py
Labels: Skip Changelog

#3826 Split serialization and export of spans into separate functions for http trace exporter
  exporter/opentelemetry-exporter-otlp-proto-http/src/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py
Labels: Skip Changelog

#3839 Update core repo approvers list
  README.md
Labels: Skip Changelog

#3811 Add shellcheck CI step
  .github/workflows/shellcheck.yml
Labels: Skip Changelog

#3835 Update importlib-metadata to 7.1
  opentelemetry-api/pyproject.toml
Labels: Skip Changelog

#3829 readthedocs: update build config
  .readthedocs.yml
Labels: Skip Changelog

#3844 Update proto version to v1.2.0
  CHANGELOG.md
  opentelemetry-proto/README.rst
  opentelemetry-proto/src/opentelemetry/proto/logs/v1/logs_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/metrics/v1/metrics_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/metrics/v1/metrics_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/trace/v1/trace_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/trace/v1/trace_pb2.pyi
  scripts/proto_codegen.sh
Labels: Approve Public API check

#3853 docs: bump jinja2 to latest in requirements
  docs/examples/fork-process-model/flask-gunicorn/requirements.txt
  docs/examples/fork-process-model/flask-uwsgi/requirements.txt
Labels: Skip Changelog

#3854 revert modifications to Apache license
  LICENSE
Labels: Skip Changelog

#3698 Sort by label keys before generating labels key and value lists
  .github/workflows/test.yml
  CHANGELOG.md
  exporter/opentelemetry-exporter-prometheus/src/opentelemetry/exporter/prometheus/__init__.py
  exporter/opentelemetry-exporter-prometheus/tests/test_prometheus_exporter.py
Labels: bug

#3831 Keep GitHub Actions up to date with GitHub's Dependabot
  .github/dependabot.yml
Labels: Skip Changelog

#3867 Update action versions
  .github/workflows/backport.yml
  .github/workflows/benchmarks.yml
  .github/workflows/changelog.yml
  .github/workflows/check-links.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/prepare-patch-release.yml
  .github/workflows/prepare-release-branch.yml
  .github/workflows/public-api-check.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: Skip Changelog

#3871 Bump black to 24.3.0
  .flake8
  dev-requirements.txt
  exporter/opentelemetry-exporter-opencensus/src/opentelemetry/exporter/opencensus/trace_exporter/__init__.py
  exporter/opentelemetry-exporter-prometheus/src/opentelemetry/exporter/prometheus/__init__.py
  opentelemetry-api/tests/propagators/test_w3cbaggagepropagator.py
  opentelemetry-sdk/src/opentelemetry/sdk/_configuration/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/_logs/_internal/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/_internal/export/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/_internal/metric_reader_storage.py
  opentelemetry-sdk/src/opentelemetry/sdk/resources/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/util/__init__.py
  opentelemetry-sdk/tests/metrics/integration_test/test_cpu_time.py
  opentelemetry-sdk/tests/metrics/integration_test/test_explicit_bucket_histogram_aggregation.py
  opentelemetry-sdk/tests/resources/test_resources.py
  shim/opentelemetry-opencensus-shim/src/opentelemetry/shim/opencensus/_shim_span.py
  shim/opentelemetry-opentracing-shim/tests/test_shim.py
Labels: Skip Changelog

#3870 Revert modifications to Apache license
  exporter/opentelemetry-exporter-opencensus/LICENSE
  exporter/opentelemetry-exporter-otlp-proto-common/LICENSE
  exporter/opentelemetry-exporter-otlp-proto-grpc/LICENSE
  exporter/opentelemetry-exporter-otlp-proto-http/LICENSE
  exporter/opentelemetry-exporter-otlp/LICENSE
  exporter/opentelemetry-exporter-prometheus/LICENSE
  exporter/opentelemetry-exporter-zipkin-json/LICENSE
  exporter/opentelemetry-exporter-zipkin-proto-http/LICENSE
  exporter/opentelemetry-exporter-zipkin/LICENSE
  opentelemetry-api/LICENSE
  opentelemetry-proto/LICENSE
  opentelemetry-sdk/LICENSE
  opentelemetry-semantic-conventions/LICENSE
  propagator/opentelemetry-propagator-b3/LICENSE
  propagator/opentelemetry-propagator-jaeger/LICENSE
  shim/opentelemetry-opencensus-shim/LICENSE
  shim/opentelemetry-opentracing-shim/LICENSE
Labels: Skip Changelog

#3880 Add --exists-action option to git checkouts for pip
  .github/workflows/test.yml
Labels: Skip Changelog

#3878 Update build.sh so opentelemetry-opencensus-shim gets published
  scripts/build.sh
Labels: Skip Changelog
