Repository open-telemetry/opentelemetry-python, pull requests merged in 2024-10, with the labels that each got.

#4209 bump pylint to 3.2.1
  dev-requirements.txt
  exporter/opentelemetry-exporter-prometheus/src/opentelemetry/exporter/prometheus/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/metrics/_internal/metric_reader_storage.py
  opentelemetry-sdk/src/opentelemetry/sdk/util/__init__.pyi
  opentelemetry-sdk/tests/metrics/exponential_histogram/test_exponent_mapping.py
  opentelemetry-sdk/tests/test_util.py
Labels: Skip Changelog

#4205 opentelemetry-api: support up to importlib-metadata 8.5.0
  opentelemetry-api/pyproject.toml
  opentelemetry-api/test-requirements.txt
Labels: Skip Changelog

#4206 Add support to protobuf5 for opentelemetry-proto and regenerate proto files
  .github/workflows/lint_0.yml
  .github/workflows/misc_0.yml
  .github/workflows/test_0.yml
  CHANGELOG.md
  docs-requirements.txt
  exporter/opentelemetry-exporter-otlp-proto-common/test-requirements.txt
  exporter/opentelemetry-exporter-otlp-proto-grpc/pyproject.toml
  exporter/opentelemetry-exporter-otlp-proto-grpc/test-requirements-0.txt
  exporter/opentelemetry-exporter-otlp-proto-grpc/test-requirements.txt
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/logs/test_otlp_logs_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/test_otlp_exporter_mixin.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/test_otlp_metrics_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/test_otlp_trace_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-http/test-requirements-0.txt
  exporter/opentelemetry-exporter-otlp-proto-http/test-requirements-1.txt
  exporter/opentelemetry-exporter-otlp-proto-http/test-requirements.txt
  exporter/opentelemetry-exporter-zipkin-proto-http/test-requirements.txt
  gen-requirements.txt
  opentelemetry-proto/pyproject.toml
  opentelemetry-proto/src/opentelemetry/proto/collector/logs/v1/logs_service_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/collector/logs/v1/logs_service_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/collector/logs/v1/logs_service_pb2_grpc.py
  opentelemetry-proto/src/opentelemetry/proto/collector/metrics/v1/metrics_service_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/collector/metrics/v1/metrics_service_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/collector/metrics/v1/metrics_service_pb2_grpc.py
  opentelemetry-proto/src/opentelemetry/proto/collector/trace/v1/trace_service_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/collector/trace/v1/trace_service_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/collector/trace/v1/trace_service_pb2_grpc.py
  opentelemetry-proto/src/opentelemetry/proto/common/v1/common_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/common/v1/common_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/logs/v1/logs_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/logs/v1/logs_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/metrics/v1/metrics_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/metrics/v1/metrics_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/resource/v1/resource_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/resource/v1/resource_pb2.pyi
  opentelemetry-proto/src/opentelemetry/proto/trace/v1/trace_pb2.py
  opentelemetry-proto/src/opentelemetry/proto/trace/v1/trace_pb2.pyi
  opentelemetry-proto/test-requirements-1.txt
  opentelemetry-proto/test-requirements.txt
  tox.ini
Labels: Approve Public API check

#4208 Record logger name as the instrumentation scope name
  CHANGELOG.md
  opentelemetry-sdk/benchmarks/logs/test_benchmark_logging_handler.py
  opentelemetry-sdk/src/opentelemetry/sdk/_logs/_internal/__init__.py
  opentelemetry-sdk/tests/logs/test_export.py
  opentelemetry-sdk/tests/logs/test_logger_provider_cache.py
Labels: Approve Public API check

#4182 sdk: Implement basic host resource detector
  CHANGELOG.md
  opentelemetry-sdk/pyproject.toml
  opentelemetry-sdk/src/opentelemetry/sdk/resources/__init__.py
  opentelemetry-sdk/tests/resources/test_resources.py
Labels: Approve Public API check

#4217 Drop `OTEL_PYTHON_EXPERIMENTAL_DISABLE_PROMETHEUS_UNIT_NORMALIZATION` environment variable
  CHANGELOG.md
  exporter/opentelemetry-exporter-prometheus/src/opentelemetry/exporter/prometheus/__init__.py
  exporter/opentelemetry-exporter-prometheus/tests/test_prometheus_exporter.py
  opentelemetry-sdk/src/opentelemetry/sdk/environment_variables/__init__.py
Labels: Approve Public API check

#4239 add contrib openai-v2 instrumentation to CI
  .github/workflows/contrib_0.yml
Labels: Skip Changelog

#4238 infra: improve tox for local development
  tox.ini
Labels: build & infra, Skip Changelog
