Repository open-telemetry/opentelemetry-python, pull requests merged in 2025-04, with the labels that each got.

#4504 Delete duplicated OTLP Exporter tests, move them to the mixin unit test. Fix broken shutdown unit test.
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/logs/test_otlp_logs_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/test_otlp_exporter_mixin.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/test_otlp_metrics_exporter.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/tests/test_otlp_trace_exporter.py
Labels: Skip Changelog

#4525 adding logging format lint check
  exporter/opentelemetry-exporter-otlp-proto-common/src/opentelemetry/exporter/otlp/proto/common/_internal/metrics_encoder/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/exporter.py
  opentelemetry-sdk/src/opentelemetry/sdk/error_handler/__init__.py
  pyproject.toml
Labels: Skip Changelog

#4545 [release/1.32.x-0.53bx] Prepare for 1.32.1
  .github/workflows/contrib.yml
  .github/workflows/lint_0.yml
  .github/workflows/misc_0.yml
  .github/workflows/test_0.yml
  .github/workflows/test_1.yml
  CHANGELOG.md
Labels: Skip generate-workflows

#4342 logs: fix serialization of Extended attributes
  CHANGELOG.md
  docs/conf.py
  exporter/opentelemetry-exporter-otlp-proto-common/src/opentelemetry/exporter/otlp/proto/common/_internal/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-common/src/opentelemetry/exporter/otlp/proto/common/_internal/_log_encoder/__init__.py
  exporter/opentelemetry-exporter-otlp-proto-common/tests/test_log_encoder.py
  opentelemetry-api/src/opentelemetry/_events/__init__.py
  opentelemetry-api/src/opentelemetry/_logs/_internal/__init__.py
  opentelemetry-api/src/opentelemetry/attributes/__init__.py
  opentelemetry-api/src/opentelemetry/util/types.py
  opentelemetry-api/tests/attributes/test_attributes.py
  opentelemetry-api/tests/events/test_proxy_event.py
  opentelemetry-api/tests/logs/test_proxy.py
  opentelemetry-sdk/src/opentelemetry/sdk/_events/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/_logs/_internal/__init__.py
  opentelemetry-sdk/tests/logs/test_log_record.py
Labels: Approve Public API check

#4535 Refactor BatchLogRecordProcessor and associated tests
  opentelemetry-sdk/src/opentelemetry/sdk/_logs/_internal/export/__init__.py
  opentelemetry-sdk/src/opentelemetry/sdk/environment_variables/__init__.py
  opentelemetry-sdk/tests/logs/test_export.py
Labels: Skip Changelog

#4547 infra: Automate SHA procedure during releases
  .github/workflows/contrib.yml
  .github/workflows/lint_0.yml
  .github/workflows/misc_0.yml
  .github/workflows/prepare-patch-release.yml
  .github/workflows/prepare-release-branch.yml
  .github/workflows/templates/lint.yml.j2
  .github/workflows/templates/misc.yml.j2
  .github/workflows/templates/test.yml.j2
  .github/workflows/test_0.yml
  .github/workflows/test_1.yml
Labels: Skip Changelog
