Repository open-telemetry/opentelemetry-python, pull requests merged in 2025-05, with the labels that each got.

#4553 Handle None in OTEL_PROPAGATORS
  CHANGELOG.md
  opentelemetry-api/src/opentelemetry/propagate/__init__.py
  opentelemetry-api/tests/propagators/test_propagators.py
Labels: Approve Public API check

#4507 opentelemetry-api: review get_logger documentation
  opentelemetry-api/src/opentelemetry/_logs/_internal/__init__.py
Labels: Skip Changelog

#4581 Updated the community calendar link in README.md to point to current valid URL
  README.md
Labels: Skip Changelog

#4575 RELEASING: update after label automation in workflows
  RELEASING.md
Labels: Skip Changelog

#4589 Backport: Fix max recursion bug by removing logging.log calls in emit (#4588)
  CHANGELOG.md
  opentelemetry-sdk/src/opentelemetry/sdk/_logs/_internal/export/__init__.py
  opentelemetry-sdk/tests/logs/test_export.py
Labels: backport

#4596 Update RELEASING.md
  RELEASING.md
Labels: Skip Changelog
